src/objects/Attribute_Adjustment__c.object
<CustomObject>
    <label>Attribute Adjustment</label>
    <nameField>
        <label>Attribute Adjustment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Attribute_Adjustment_Item__c.object
<CustomObject>
    <fields>
        <fullName>Adj_Type__c</fullName>
        <label>Adj Type</label>
        <picklist>
            <picklistValues>
                <fullName>Markup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AddOnAmount</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>AddOnPercent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Adj_Value__c</fullName>
        <label>Adj Value</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Attribute_Adjustment__c</fullName>
        <label>Attribute Adjustment</label>
        <referenceTo>Attribute_Adjustment__c</referenceTo>
        <relationshipLabel>Attribute Adjustment Items</relationshipLabel>
        <relationshipName>Attribute_Adjustment_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attribute_Name__c</fullName>
        <label>Attribute Name</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Attribute_Value__c</fullName>
        <label>Attribute Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Attribute Adjustment Item</label>
    <nameField>
        <label>Attribute Adjustment Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Adjustment Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/REVVY__MnQiSubLineAttribute__c.object
<CustomObject>
    <fields>
        <fullName>OCD_AName__c</fullName>
        <formula>REVVY__CatalogAttribute__r.Name</formula>
        <label>AName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCD_Attrib_Value__c</fullName>
        <label>OCD Attrib Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__ActualValue__c</fullName>
        <label>ActualValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__AttributeValue__c</fullName>
        <label>AttributeValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__CatalogAttribute__c</fullName>
        <label>CatalogAttribute</label>
        <referenceTo>REVVY__MnCatalogAttribute__c</referenceTo>
        <relationshipLabel>QiSubLineAttributes</relationshipLabel>
        <relationshipName>QiSubLineAttributes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>REVVY__QuoteItemSubLine__c</fullName>
        <label>QuoteItemSubLine</label>
        <referenceTo>REVVY__MnQuoteItemSubLine__c</referenceTo>
        <relationshipLabel>QiSubLineAttributes</relationshipLabel>
        <relationshipName>QiSubLineAttributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>equipmentName__c</fullName>
        <label>Equipment Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>serialNumber__c</fullName>
        <label>Serial Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tradeInValue__c</fullName>
        <label>Trade-In Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <displayFormat>Q{00000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>ID</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Attribute_Adjustment_Id__c</fullName>
        <label>Attribute Adjustment Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>Quote Item ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItemSubLine__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Attribute_Adjustment_Id__c</fullName>
        <label>Attribute Adjustment Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Deprecated</description>
        <externalId>true</externalId>
        <inlineHelpText>Deprecated</inlineHelpText>
        <label>Deprecated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/OCDAttributePricingTest.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @group Get Price
* @group-content ../../ApexDocContent/OCDAttributePricingTest.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

@isTest
private class OCDAttributePricingTest {

    @testSetup static void loadData() {
		OCD_TestData.createCLTestData();
	}
	
	static testMethod void adjustAttributePricesTest()
	{
		Attribute_Adjustment__c att = new Attribute_Adjustment__c(Name='Package Test');
		insert att;
		Attribute_Adjustment_Item__c aai = new Attribute_Adjustment_Item__c(Name='Package Test Item 1', Attribute_Value__c='1', 
			Attribute_Name__c='Package', Adj_Value__c=500, Adj_Type__c='AddOnAmount', Attribute_Adjustment__c=att.Id);
		insert aai;
		
		//REVVY__MnCatalogAttribute__c 
		//Select r.tradeInValue__c, r.serialNumber__c, r.equipmentName__c, r.REVVY__QuoteItemSubLine__c, 
		//r.REVVY__CatalogAttribute__c, r.REVVY__AttributeValue__c, r.REVVY__ActualValue__c, r.OCD_Attrib_Value__c, 
		//r.OCD_AName__c, r.Name, r.Id From REVVY__MnQiSubLineAttribute__c r
		
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId = null;
		try{ 
			
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName); 
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);          
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
			List<REVVY__MnQiSubLineAttribute__c> qislas = new List<REVVY__MnQiSubLineAttribute__c>();
			for(REVVY__MnQuoteItemSubLine__c qisl : qlItemSublines) {
				qislas.add( new REVVY__MnQiSubLineAttribute__c(
					REVVY__CatalogAttribute__r = new REVVY__MnCatalogAttribute__c(REVVY__Id__c='Package'),
					OCD_Attrib_Value__c = '100',
					REVVY__ActualValue__c = '100',
					REVVY__AttributeValue__c='100',
					REVVY__QuoteItemSubLine__c = qisl.Id
					));
				qisl.OCD_Attribute_Adjustment_Id__c = att.id;
			}
			insert qislas;
			update qlItemSublines;
			
			for(REVVY__MnQuoteItem__c qi : qlItems ) {
				qi.OCD_Attribute_Adjustment_Id__c = att.id;
			}
			update qlItems;
	        OCDQuotePricingInfo ocdPrInfo = new OCDQuotePricingInfo();
			ocdPrInfo.qLIList = qlItems;
			ocdPrInfo.quoteHeaderObj = quoteHeaderObj;
			ocdPrInfo.qSubLIList = qlItemSublines;
			
			OCDAttributePricing ocdY = new OCDAttributePricing();
			ocdPrInfo = ocdY.adjustAttributePrices(ocdPrInfo);
	         
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
	} //End updateAllPricesExcStrateg
}