src/objects/Deal_Assessment_Cost__c.object
<CustomObject>
    <description>Other Cost</description>
    <fields>
        <fullName>Cost__c</fullName>
        <inlineHelpText>Other Cost</inlineHelpText>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deal_Assessment__c</fullName>
        <label>Deal Assessment</label>
        <referenceTo>OCD_Deal_Assessment__c</referenceTo>
        <relationshipName>Deal_Assessment_Cost</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote_ID__c</fullName>
        <formula>CASESAFEID( Deal_Assessment__r.Quote__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quote ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <formula>Quantity__c *  Cost__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type: One Time or Recurring</description>
        <inlineHelpText>One Time or Recurring</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>One Time</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Assessment Cost</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Assessment Cost</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OCD_Deal_Assessment__c.object
<CustomObject>
    <description>Deal Assessment Summary</description>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>REVVY__MnQuote__c</referenceTo>
        <relationshipName>Deal_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Cost__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Financial Assessment</label>
    <nameField>
        <label>Deal Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/REVVY__MnQuote__c.object
<CustomObject>
</CustomObject>

src/classes/OCD_DACostController.cls
/**
* @author Indra Lugina
* @date 10/10/2016 
*
* @group FinancialAssessment
* @group-content ../../ApexDocContent/OCD_DACostController.htm 
*
* @description Financial Assement Display Controller
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Indra Lugina        10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

public class OCD_DACostController {

    /*********************************************************************************************
    * @description class variables
    **********************************************************************************************/
	List<String> dacFieldsList = new List<String> {'Id','Name', 'Product_Description__c', 'Deal_Assessment__c','Quote_ID__c', 'Quantity__c', 'Cost__c', 'Type__c','Total_Cost__c'};
	public Deal_Assessment_Cost__c dac {get;set;}
	public String sid {get;set;}
	public Deal_Assessment_Cost__c newDACost {get;set;}
	public List<Deal_Assessment_Cost__c> dacList {get;set;}
	public String delDACId {get;set;}
	public OCD_Deal_Assessment__c da {get;set;}

    /*********************************************************************************************
    * @description constructor
    * @param ApexPages.StandardSetController controller
    **********************************************************************************************/
    public OCD_DACostController(ApexPages.StandardSetController controller) {
		sid = ApexPages.Currentpage().getParameters().get('id');
		dac = new Deal_Assessment_Cost__c(Deal_Assessment__c=sid);
		init();
    }

    /*********************************************************************************************
    * @description constructor
    * @param ApexPages.StandardController controller
    **********************************************************************************************/
    public OCD_DACostController(ApexPages.StandardController controller) {
    	if (!Test.isRunningTest()) {
			controller.addFields(dacFieldsList);  
    	}  	
		sid = controller.getId();     
		dac = (Deal_Assessment_Cost__c) controller.getRecord();		
		init();
    }

    /*********************************************************************************************
    * @description Redirect to DA Cost
    * @return PageReference
    **********************************************************************************************/
	public PageReference redirectToDACost() {
		
		String daId='';
		sid = ApexPages.Currentpage().getParameters().get('id');
		if(!String.isEmpty(sid)) {
			List<Deal_Assessment_Cost__c> daIdObj = [Select Id, Deal_Assessment__c From Deal_Assessment_Cost__c where Id =:sid];
			if(daIdObj.size()>0) {
				daId = daIdObj[0].Deal_Assessment__c;
			}
		}
		PageReference pg = Page.OCD_DACost;
		pg.getParameters().put('id',daId);		
		pg.setRedirect(true);
		return pg;
	}

    /*********************************************************************************************
    * @description Initialize
    **********************************************************************************************/
	public void init() {
		delDACId = '';
		newDACost = new Deal_Assessment_Cost__c();
		readDealAssessmentCost();
		if(dac!=null && dac.Deal_Assessment__c!=null) {
			da = [Select Id, Quote__c, Quote__r.CurrencyIsoCode From OCD_Deal_Assessment__c where Id = :dac.Deal_Assessment__c];
		}	
	}
	
    /*********************************************************************************************
    * @description Add financial assessment cost
    **********************************************************************************************/
	public void addDAC() {
		if(dac!=null && dac.Deal_Assessment__c!=null) {
			newDACost.Deal_Assessment__c = dac.Deal_Assessment__c;
			newDACost.CurrencyIsoCode = da.Quote__r.CurrencyIsoCode;
			insert newDACost;
			updateDealAssessment(da.Quote__c); 			
			newDACost = new Deal_Assessment_Cost__c();
			readDealAssessmentCost();
		}
		
	}

    /*********************************************************************************************
    * @description Return to Quote
    * @return PageReference
    **********************************************************************************************/
	public PageReference returnToDA() {
		
		updateDealAssessment(da.Quote__c); 	
		return cancelToDA();		
	}	
	
    /*********************************************************************************************
    * @description Cancel and redirecto Financial Assessment
    * @return PageReference
    **********************************************************************************************/
	public PageReference cancelToDA() {		
		PageReference pg = new PageReference('/'+dac.Deal_Assessment__c);
		pg.setRedirect(true);
		return pg;		
	}		
	
    /*********************************************************************************************
    * @description Read financial assessment cost
    **********************************************************************************************/
	public void readDealAssessmentCost() {
		dacList = new List<Deal_Assessment_Cost__c>();
		if(dac!=null && dac.Deal_Assessment__c!=null) {
			for(Deal_Assessment_Cost__c dac:[Select Id, Name, Product_Description__c, Deal_Assessment__c, Quote_Id__c, Quantity__c, Cost__c, Type__c, Total_Cost__c
			                                   From Deal_Assessment_Cost__c
			                                  Where Deal_Assessment__c = :dac.Deal_Assessment__c] ) {
				dacList.add(dac);                                  	
			}
		}
	}
	
    /*********************************************************************************************
    * @description Delete financial assessment cost
    **********************************************************************************************/
	public void deleteDAC() {
		if(!String.isEmpty(delDACId)) {
			delete [Select Id From Deal_Assessment_Cost__c where Id=:delDACId];
			updateDealAssessment(da.Quote__c); 			
			newDACost = new Deal_Assessment_Cost__c();
			readDealAssessmentCost();
		}
	}
	
    /*********************************************************************************************
    * @description Update financial assessment cost
    **********************************************************************************************/
	public void updateDealAssessment(String quoteId) {
		if(!String.isEmpty(quoteId)) {
			OCD_DAUtility2 daUtil = new OCD_DAUtility2();
			daUtil.calculate(quoteId);	
		}
	}
}