src/objects/Deal_Assessment_Cost__c.object
<CustomObject>
    <description>Other Cost</description>
    <fields>
        <fullName>Cost__c</fullName>
        <inlineHelpText>Other Cost</inlineHelpText>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Deal_Assessment__c</fullName>
        <label>Deal Assessment</label>
        <referenceTo>OCD_Deal_Assessment__c</referenceTo>
        <relationshipName>Deal_Assessment_Cost</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Product_Description__c</fullName>
        <label>Product Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type: One Time or Recurring</description>
        <inlineHelpText>One Time or Recurring</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>One Time</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Recurring</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financial Assessment Cost</label>
    <nameField>
        <label>Product Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Assessment Cost</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OCD_Deal_Assessment__c.object
<CustomObject>
    <description>Deal Assessment Summary</description>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>REVVY__MnQuote__c</referenceTo>
        <relationshipName>Deal_Assessments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Assessment</label>
    <nameField>
        <label>Deal Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Term_Months__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Term(Months)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REVVY__Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Unique ID of the account that is associated with the quote.</description>
        <inlineHelpText>Unique ID of the account that is associated with the quote.</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <errorMessage>You should assign only group accounts to group quotes</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Group Quote</value>
            </filterItems>
            <filterItems>
                <field>Account.REVVY__MnIsGroupAccount__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Group Quote</value>
            </filterItems>
            <filterItems>
                <field>Account.REVVY__MnIsGroupAccount__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Revvy Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Unique ID of the sales opportunity associated with this quote.</description>
        <inlineHelpText>Unique ID of the sales opportunity associated with this quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Revvy Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/OCD_DACostControllerTest.cls
/**
* @author Indra Lugina
* @date 10/10/2016 
*
* @group FinancialAssessment
* @group-content ../../ApexDocContent/OCD_DACostControllerTest.htm 
*
* @description Financial Assement Display Controller Test Class
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Indra Lugina        10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

@isTest
private class OCD_DACostControllerTest {
@testSetup static void loadData() {
		OCD_TestData.createCLTestData();
	}
    static testMethod void myUnitTest() {
    	String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId = null;
		try{ 
			
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName); 
			Account acc = [select id from Account where name = 'Kim Montz CPQ Pilot Test Account' limit 1];
	        acc.phone = '5555555555';
	        acc.BillingPostalCode = '14618';
	        acc.BillingCity = 'Rochester';
	        acc.BillingCountry = 'United States';
	        update acc;
	        Id pricebookId = Test.getStandardPricebookId();
	        Opportunity testOpp = new Opportunity(AccountId= acc.Id, Pricebook2Id = pricebookId,  Name = 'testOpp', StageName = 'Qualify', CloseDate = Date.today(), Overall_Acquisition_Type__c = 'KAI', Agreement_Term_Months__c = 60);
    		insert testOpp;
    		quoteHeaderObj.REVVY__Opportunity__c = testOpp.Id;
    		quoteHeaderObj.REVVY__Account__c = acc.Id;
    		quoteHeaderObj.OCD_Term_Months__c = 144;
    		update quoteHeaderObj;
            Test.startTest();
			PageReference pageRef = Page.OCD_DACalculation;
        	Test.setCurrentPage(pageRef);
        	ApexPages.StandardController sc = new ApexPages.standardController(quoteHeaderObj);
        	OCD_DACalcController controller = new OCD_DACalcController(sc);
        	controller.init();
        	OCD_Deal_Assessment__c da = [Select o.Id, Quote__c From OCD_Deal_Assessment__c o limit 1];
        	
        	Deal_Assessment_Cost__c dac = new Deal_Assessment_Cost__c(Name='Test', PRODUCT_DESCRIPTION__C = 'Test', QUANTITY__C=1, COST__C=1000, TYPE__C='One Time', DEAL_ASSESSMENT__C=da.Id);
        	//insert dac;
        	pageRef = Page.OCD_DACost;
        	Test.setCurrentPage(pageRef);
        	
        	List<Deal_Assessment_Cost__c> dacs = new List<Deal_Assessment_Cost__c>{dac};
			ApexPages.StandardSetController sc3 = new ApexPages.StandardSetController(dacs);
			sc3.setSelected(dacs);
			
        	ApexPages.StandardController sc2 = new ApexPages.standardController(dac);
        	
        	OCD_DACostController controller2 = new OCD_DACostController(sc3); 
        	controller2 = new OCD_DACostController(sc2);
        	controller2.newDACost = dac;
        	
        	controller2.addDAC();
        	controller2.delDACId = da.Id;
        	controller2.da = da;
        	controller2.returnToDA();
        	controller2.redirectToDACost();
        	controller2.deleteDAC();
        	
        	Test.stopTest();
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
        
    }
    
}