src/objects/Discount_Item__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Discount Items</relationshipLabel>
        <relationshipName>Discount_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Discount Item</label>
    <nameField>
        <label>Discount Item Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discount Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/OCD_Beh_Discount_Item__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Beh_Discount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCD Beh Discount</label>
        <referenceTo>OCD_Beh_Discount__c</referenceTo>
        <relationshipLabel>Discount Items</relationshipLabel>
        <relationshipName>OCD_Beh_Discount_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OCD Beh Discount Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCD Beh Discount Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OCD_Beh_Eligibility__c.object
<CustomObject>
    <description>Behavioural Discount Eligibility Conditions will be stored in this Object.</description>
    <fields>
        <fullName>OCD_Beh_Discount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCD Beh Discount</label>
        <referenceTo>OCD_Beh_Discount__c</referenceTo>
        <relationshipLabel>Eligibility</relationshipLabel>
        <relationshipName>OCD_Beh_Eligibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>OCD Beh Eligibility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCD Beh Eligibilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/REVVY__MnCatalogNode__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/REVVY__MnPriceList__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associate with Discount Record</description>
        <label>Discount</label>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>Price_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OCD_Beh_Discount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Behavioral Discount</label>
        <referenceTo>OCD_Beh_Discount__c</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>Price_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>Price List ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/REVVY__MnPriceListLine__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volume Discount</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Discount__c.Level_Applied__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Price List Lines</relationshipLabel>
        <relationshipName>Discount_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>Price List Line ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>MultiFamily__c</fullName>
        <defaultValue>false</defaultValue>
        <description>User to check Multi Family Eligibility and check this box if Quote is eligible for Multi Family discount.</description>
        <inlineHelpText>Please check Multi Family Eligibility and check this box if Quote is eligible for Multi Family discount</inlineHelpText>
        <label>MultiFamily</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OCD_CAT_Accessories_Discount__c</fullName>
        <description>CAT Accessories Discount</description>
        <label>CAT Accessories Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CAT_Consumable_Discount__c</fullName>
        <description>CAT Consumable Discount</description>
        <label>CAT Consumable Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CAT_Equipment_Discount__c</fullName>
        <description>CAT Equipment Discount</description>
        <label>CAT Equipment Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CAT_Other_Discount__c</fullName>
        <label>CAT Other Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CAT_Service_Discount__c</fullName>
        <label>CAT Service Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CAT_Volume_Disc__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Canada CAT Volume Disc</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_Quote_Type__c</fullName>
        <inlineHelpText>Purchase, Lease, Monthly Payment, CPRR, CPT, Reagent Rental, Managed Service</inlineHelpText>
        <label>Quote Type</label>
        <picklist>
            <picklistValues>
                <fullName>Purchase</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPRR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reagent Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDN Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_TradIH_Accessories_Discount__c</fullName>
        <label>TradIH Accessories Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_TradIH_Consumable_Discount__c</fullName>
        <label>TradIH Consumable Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_TradIH_Equipment_Discount__c</fullName>
        <label>TradIH Equipment Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_TradIH_Other_Discount__c</fullName>
        <label>TradIH Other Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_TradIH_Service_Discount__c</fullName>
        <label>TradIH Service Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_TradIH_Volume_Disc__c</fullName>
        <defaultValue>0</defaultValue>
        <label>TradIH Volume Disc</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <displayFormat>Q{00000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>ID</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>Quote Item ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItemSubLine__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Deprecated</description>
        <externalId>true</externalId>
        <inlineHelpText>Deprecated</inlineHelpText>
        <label>Deprecated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/OCD_QuotePriceLookupIHTest.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @group Get Price
* @group-content ../../ApexDocContent/OCD_QuotePriceLookupIHTest.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

@isTest
private class OCD_QuotePriceLookupIHTest
{
    @testSetup static void loadData() {
    	OCD_TestData.createIHTestData(); 
    	/*
		Test.loadData(OCD_Interest_Rate__c.sObjectType, 'UTC_OCDInterestRateImport');
		Test.loadData(REVVY__MnCatalogAttribute__c.sObjectType, 'UTC_CatalogAttributeImport');
		Test.loadData(REVVY__MnCatalogAttributeValue__c.sObjectType, 'UTC_CatalogAttributeValueImport');
		Test.loadData(Discount__c.sObjectType, 'UTC_Discount');
		Test.loadData(Discount_Item__c.sObjectType, 'UTC_Discount_Item');
		Test.loadData(OCD_Beh_Discount__c.sObjectType, 'UTC_BEH_Discount');
		Test.loadData(OCD_Beh_Discount_Item__c.sObjectType, 'UTC_BEH_Discount_Item');
		Test.loadData(OCD_Beh_Eligibility__c.sObjectType, 'UTC_BehEligibilityImport');
		Test.loadData(Account.sObjectType, 'UTC_Account');
		Test.loadData(REVVY__MnConfigEngineModel__c.sObjectType, 'UTC_ModelImport');
		Test.loadData(REVVY__MnCatalogNode__c.sObjectType, 'UTC_CatalogImport');
		Test.loadData(REVVY__MnCatalogNode__c.sObjectType, 'UTC_ParentCategoryImport');
		Test.loadData(REVVY__MnCatalogNode__c.sObjectType, 'UTC_IH_ParentCategory');
		Test.loadData(REVVY__MnCatalogNode__c.sObjectType, 'UTC_IH_CategoryImport');
		Test.loadData(REVVY__MnCatalogNode__c.sObjectType, 'UTC_IH_CatalogNodeImport');
		//Test.loadData(REVVY__MnCatalogNode__c.sObjectType, 'UTC_SolutionImport');
		Test.loadData(REVVY__MnCatalogNodeEdge__c.sObjectType, 'UTC_IH_CatalogNodeEdge');
		Test.loadData(REVVY__MnPriceList__c.sObjectType, 'UTC_CL_PriceListImport');
		Test.loadData(REVVY__MnPriceListLine__c.sObjectType, 'UTC_IH_PriceListItemImport');
		Test.loadData(REVVY__MnQuote__c.sObjectType, 'UTC_IH_QuoteImport');
		//Test.loadData(REVVY__MnQuoteSolution__c.sObjectType, 'UTC_QuoteSolutionImport');
		Test.loadData(REVVY__MnQuoteItem__c.sObjectType, 'UTC_IH_QuoteItemImport');
		//Test.loadData(REVVY__MnQuoteItemSubLine__c.sObjectType, 'UTC_IH_QuoteItemImport');
		*/
	}
	static testMethod void StrategicDiscountTest()
	{
		String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_CAT_Accessories_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Consumable_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Equipment_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Service_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Other_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Volume_Disc__c=2;
				
				quoteHeaderObj.OCD_TradIH_Accessories_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Consumable_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Equipment_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Service_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Other_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Volume_Disc__c=2;
				
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		} 

		Test.stopTest();
		
	} //end static testMethod void getPricesTest()
	
	static testMethod void purchaseGetPricesTest()
	{
		String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
			//msg = OCDQuotePriceLookup.resetPrices(quoteId);
			
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		} 

		Test.stopTest();
		
	} //end static testMethod void getPricesTest()
	static testMethod void multifamilyGetPricesTest()
	{
		String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.MultiFamily__c=true;
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
			
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} //end static testMethod void getPricesTest()
	
	static testMethod void leaseGetPricesTest()
	{
		String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'Lease';
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 
	
	static testMethod void reagentRentalGetPricesTest()
	{
		String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'Reagent Rental';
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 
	
	static testMethod void cptGetPricesTest()
	{
		String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'CPT';
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 
	
	static testMethod void managedServicesGetPricesTest()
	{
		String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'Managed Services';
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 
	static testMethod void idnMemberGetPricesTest()
	{
		String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'IDN Member';
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 
	
	static testMethod void monthlyRentalGetPricesTest()
	{
		String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'Monthly Rental';
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 
	
	static testMethod void cprrGetPricesTest()
	{
		String quoteName = 'IH Test Case 9';
		String sharedConsumables = '6801715';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'CPRR';
				update quoteHeaderObj;
			}
			
			List<REVVY__MnCatalogNode__c> prods = [Select Id From REVVY__MnCatalogNode__c r where REVVY__Id__c = :sharedConsumables OR REVVY__Id__c = '6801744'];
			for(REVVY__MnCatalogNode__c p : prods) {
				p.LOB__c = 'CC;IA';
			}
			update prods;
			
			List<REVVY__MnQuoteItem__c> qItems =  [Select Id, r.REVVY__Quantity__c, r.REVVY__Product_ID_F__c From REVVY__MnQuoteItem__c r 
													where REVVY__Product_ID_F__c= :sharedConsumables and REVVY__Quote__r.Name= :quoteName];
			List<REVVY__MnQuoteItemAttribute__c> qias = new List<REVVY__MnQuoteItemAttribute__c>();
			
			for(REVVY__MnQuoteItem__c qi : qItems) {
				qias.add(new REVVY__MnQuoteItemAttribute__c(REVVY__QuoteItem__c = qi.Id, REVVY__AttributeValue__c = '131', REVVY__ActualValue__c='131', ccQty__c=131,
								REVVY__CatalogAttribute__r = new REVVY__MnCatalogAttribute__c(REVVY__Id__c='ccQty')));
				qias.add(new REVVY__MnQuoteItemAttribute__c(REVVY__QuoteItem__c = qi.Id, REVVY__AttributeValue__c = '100', REVVY__ActualValue__c='100', iaQty__c=100,
								REVVY__CatalogAttribute__r = new REVVY__MnCatalogAttribute__c(REVVY__Id__c='iaQty')));
			}
			insert qias;
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 

}