src/objects/Discount_Item__c.object
<CustomObject>
    <fields>
        <fullName>Adj_Type__c</fullName>
        <label>Adj Type</label>
        <picklist>
            <picklistValues>
                <fullName>Percent</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Markup</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <defaultValue>&quot;USA&quot;</defaultValue>
        <description>To identify country specific discount</description>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Code__c</fullName>
        <defaultValue>&quot;Volume Discount&quot;</defaultValue>
        <label>Discount Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Group__c</fullName>
        <description>This field should be unique across the PL. Generate a name with PL + Number</description>
        <inlineHelpText>Applicable to Group Volume.(This field should be unique across the PL. Generate a name with PL + Number)</inlineHelpText>
        <label>Discount Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <picklist>
            <picklistValues>
                <fullName>Volume</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GroupVolume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GroupVolumeRBC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Discount Items</relationshipLabel>
        <relationshipName>Discount_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Max_Adj_Amount__c</fullName>
        <label>Max Adj Amount</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Qty__c</fullName>
        <label>Max Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Adj_Amount__c</fullName>
        <label>Min Adj Amount</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Qty__c</fullName>
        <label>Min Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Products_Applied_On__c</fullName>
        <description>Applicable only for GroupVolume</description>
        <inlineHelpText>Applicable only for GroupVolume</inlineHelpText>
        <label>Products Applied On</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_Based_On__c</fullName>
        <description>Applicable only for GroupVolume.</description>
        <inlineHelpText>Applicable only for GroupVolume.</inlineHelpText>
        <label>Products Based On</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Discount Item</label>
    <nameField>
        <label>Discount Item Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discount Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/REVVY__MnPriceList__c.object
<CustomObject>
    <fields>
        <fullName>Country_applicability__c</fullName>
        <description>ocd</description>
        <label>Country applicability</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Associate with Discount Record</description>
        <label>Discount</label>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>Price_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>Price List ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>OCD_CAT_Accessories_Discount__c</fullName>
        <description>CAT Accessories Discount</description>
        <label>CAT Accessories Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CAT_Consumable_Discount__c</fullName>
        <description>CAT Consumable Discount</description>
        <label>CAT Consumable Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CAT_Equipment_Discount__c</fullName>
        <description>CAT Equipment Discount</description>
        <label>CAT Equipment Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CAT_Other_Discount__c</fullName>
        <label>CAT Other Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CAT_Service_Discount__c</fullName>
        <label>CAT Service Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CAT_Volume_Disc__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Canada CAT Volume Disc</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CC_Volume_Disc__c</fullName>
        <defaultValue>0</defaultValue>
        <label>CC Volume Disc</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_IA_Volume_Disc__c</fullName>
        <defaultValue>0</defaultValue>
        <label>IA Volume Disc</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_TradIH_Accessories_Discount__c</fullName>
        <label>TradIH Accessories Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_TradIH_Consumable_Discount__c</fullName>
        <label>TradIH Consumable Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_TradIH_Equipment_Discount__c</fullName>
        <label>TradIH Equipment Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_TradIH_Other_Discount__c</fullName>
        <label>TradIH Other Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_TradIH_Service_Discount__c</fullName>
        <label>TradIH Service Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_TradIH_Volume_Disc__c</fullName>
        <defaultValue>0</defaultValue>
        <label>TradIH Volume Disc</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <displayFormat>Q{00000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>ID</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>Quote Item ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItemSubLine__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Deprecated</description>
        <externalId>true</externalId>
        <inlineHelpText>Deprecated</inlineHelpText>
        <label>Deprecated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/OCDIHSpecificDiscountCalcTest.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @group Get Price
* @group-content ../../ApexDocContent/OCDIHSpecificDiscountCalcTest.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

@isTest
private class OCDIHSpecificDiscountCalcTest {
	@testSetup static void loadData() {
    	OCD_TestData.createIHTestData(); 
	}
    static testMethod void myUnitTest() {
        String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			Discount__c d = [Select d.Id From Discount__c d where Name='US CC Discounts 2015' limit 1];
			List<Discount_Item__c> discountItems = new List<Discount_Item__c>{
				new Discount_Item__c(PRODUCTS_BASED_ON__C='MTS084014,MTS084024,MTS085014,MTS080014,MTS080015,MTS080016,MTS080017,MTS080024,MTS080210,MTS080212,MTS080310,MTS080312,MTS080515,MTS081001,MTS081115,MTS081222',
									PRODUCTS_APPLIED_ON__C='MTS084014,MTS084024,MTS085014',
									MIN_QTY__C=9601, MIN_ADJ_AMOUNT__C=15.5, MAX_QTY__C=24000, MAX_ADJ_AMOUNT__C=17.5, 
									DISCOUNT_TYPE__C = 'GroupVolume',
									DISCOUNT_GROUP__C = 'US CAT igG',
									DISCOUNT_CODE__C = 'Volume Discount',
									DISCOUNT__C=d.Id,
									ADJ_TYPE__C='Percent',
									COUNTRY__C='US'),
				new Discount_Item__c(PRODUCTS_BASED_ON__C='MTS084014,MTS084024,MTS085014,MTS080014,MTS080015,MTS080016,MTS080017,MTS080024,MTS080210,MTS080212,MTS080310,MTS080312,MTS080515,MTS081001,MTS081115,MTS081222',
									PRODUCTS_APPLIED_ON__C='MTS084014,MTS084024,MTS085014',
									MIN_QTY__C=9601, MIN_ADJ_AMOUNT__C=15.5, MAX_QTY__C=24000, MAX_ADJ_AMOUNT__C=17.5, 
									DISCOUNT_TYPE__C = 'GroupVolume',
									DISCOUNT_GROUP__C = 'US CAT aboRh',
									DISCOUNT_CODE__C = 'Volume Discount',
									DISCOUNT__C=d.Id,
									ADJ_TYPE__C='Percent',
									COUNTRY__C='US'),
				new Discount_Item__c(PRODUCTS_BASED_ON__C='MTS084014,MTS084024,MTS085014,MTS080014,MTS080015,MTS080016,MTS080017,MTS080024,MTS080210,MTS080212,MTS080310,MTS080312,MTS080515,MTS081001,MTS081115,MTS081222',
									PRODUCTS_APPLIED_ON__C='MTS084014,MTS084024,MTS085014',
									MIN_QTY__C=9601, MIN_ADJ_AMOUNT__C=15.5, MAX_QTY__C=24000, MAX_ADJ_AMOUNT__C=17.5, 
									DISCOUNT_TYPE__C = 'GroupVolume',
									DISCOUNT_GROUP__C = 'CA Trad Group Discounts RBC',
									DISCOUNT_CODE__C = 'Volume Discount',
									DISCOUNT__C=d.Id,
									ADJ_TYPE__C='Percent',
									COUNTRY__C='US')				
									
			};
			insert discountItems;
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id); 
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_CAT_Accessories_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Consumable_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Equipment_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Service_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Other_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Volume_Disc__c=2;
				
				quoteHeaderObj.OCD_TradIH_Accessories_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Consumable_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Equipment_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Service_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Other_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Volume_Disc__c=2;
				
				update quoteHeaderObj;
			}
			
			OCDQuotePricingInfo ocdPrInfo = new OCDQuotePricingInfo();
			ocdPrInfo.qLIList = qlItems;
			ocdPrInfo.quoteHeaderObj = quoteHeaderObj;
			ocdPrInfo.qSubLIList = qlItemSublines;
			quoteHeaderObj.OCD_IA_Volume_Disc__c = 15;
			quoteHeaderObj.OCD_CC_Volume_Disc__c = 15;
			OCDSpecificDiscountCalc calc = new OCDSpecificDiscountCalc();
			calc.updateNonStdVolumeDiscounts(quoteHeaderObj, qlItems, ocdPrInfo, d.id, d.id, d.id, d.id);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		} 

		Test.stopTest();
        
    }
    static testMethod void myUnitTest2() {
        String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId=null;
		List<REVVY__MnPriceList__c> pls = [Select r.REVVY__Id__c, r.Id From REVVY__MnPriceList__c r];
		for(REVVY__MnPriceList__c pl : pls) {
			pl.Country_applicability__c = 'CA';
		}
		
		update pls;
			
		Test.startTest();
		try{
			Discount__c d = [Select d.Id From Discount__c d where Name='US CC Discounts 2015' limit 1];
			List<Discount_Item__c> discountItems = new List<Discount_Item__c>{
				new Discount_Item__c(PRODUCTS_BASED_ON__C='MTS084014,MTS084024,MTS085014,MTS080014,MTS080015,MTS080016,MTS080017,MTS080024,MTS080210,MTS080212,MTS080310,MTS080312,MTS080515,MTS081001,MTS081115,MTS081222',
									PRODUCTS_APPLIED_ON__C='MTS084014,MTS084024,MTS085014',
									MIN_QTY__C=9601, MIN_ADJ_AMOUNT__C=15.5, MAX_QTY__C=24000, MAX_ADJ_AMOUNT__C=17.5, 
									DISCOUNT_TYPE__C = 'GroupVolume',
									DISCOUNT_GROUP__C = 'US CAT igG',
									DISCOUNT_CODE__C = 'Volume Discount',
									DISCOUNT__C=d.Id,
									ADJ_TYPE__C='Percent',
									COUNTRY__C='CA'),
				new Discount_Item__c(PRODUCTS_BASED_ON__C='MTS084014,MTS084024,MTS085014,MTS080014,MTS080015,MTS080016,MTS080017,MTS080024,MTS080210,MTS080212,MTS080310,MTS080312,MTS080515,MTS081001,MTS081115,MTS081222',
									PRODUCTS_APPLIED_ON__C='MTS084014,MTS084024,MTS085014',
									MIN_QTY__C=9601, MIN_ADJ_AMOUNT__C=15.5, MAX_QTY__C=24000, MAX_ADJ_AMOUNT__C=17.5, 
									DISCOUNT_TYPE__C = 'GroupVolume',
									DISCOUNT_GROUP__C = 'US CAT aboRh',
									DISCOUNT_CODE__C = 'Volume Discount',
									DISCOUNT__C=d.Id,
									ADJ_TYPE__C='Percent',
									COUNTRY__C='CA'),
				new Discount_Item__c(PRODUCTS_BASED_ON__C='MTS084014,MTS084024,MTS085014,MTS080014,MTS080015,MTS080016,MTS080017,MTS080024,MTS080210,MTS080212,MTS080310,MTS080312,MTS080515,MTS081001,MTS081115,MTS081222',
									PRODUCTS_APPLIED_ON__C='MTS084014,MTS084024,MTS085014',
									MIN_QTY__C=9601, MIN_ADJ_AMOUNT__C=15.5, MAX_QTY__C=24000, MAX_ADJ_AMOUNT__C=17.5, 
									DISCOUNT_TYPE__C = 'GroupVolume',
									DISCOUNT_GROUP__C = 'CA Trad Group Discounts RBC',
									DISCOUNT_CODE__C = 'Volume Discount',
									DISCOUNT__C=d.Id,
									ADJ_TYPE__C='Percent',
									COUNTRY__C='CA')				
									
			};
			insert discountItems;
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			quoteHeaderObj.OCD_Billing_ISO_Country_Code__c = 'CA';
			update quoteHeaderObj;
			
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id); 
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_CAT_Accessories_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Consumable_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Equipment_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Service_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Other_Discount__c=2;
				quoteHeaderObj.OCD_CAT_Volume_Disc__c=2;
				
				quoteHeaderObj.OCD_TradIH_Accessories_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Consumable_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Equipment_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Service_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Other_Discount__c=2;
				quoteHeaderObj.OCD_TradIH_Volume_Disc__c=2;
				
				update quoteHeaderObj;
			}
			
			OCDQuotePricingInfo ocdPrInfo = new OCDQuotePricingInfo();
			ocdPrInfo.qLIList = qlItems;
			ocdPrInfo.quoteHeaderObj = quoteHeaderObj;
			ocdPrInfo.qSubLIList = qlItemSublines;
			quoteHeaderObj.OCD_IA_Volume_Disc__c = 15;
			quoteHeaderObj.OCD_CC_Volume_Disc__c = 15;
			OCDSpecificDiscountCalc calc = new OCDSpecificDiscountCalc();
			calc.updateNonStdVolumeDiscounts(quoteHeaderObj, qlItems, ocdPrInfo, d.id, d.id, d.id, d.id);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		} 

		Test.stopTest();
        
    }
}