src/objects/Discount__c.object
<CustomObject>
    <description>Discount Header which should be associated to the Price Plan.</description>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Discount_Item__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <defaultValue>&quot;USA&quot;</defaultValue>
        <description>To identify country specific discount</description>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Discount Items</relationshipLabel>
        <relationshipName>Discount_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Products_Based_On__c</fullName>
        <description>Applicable only for GroupVolume.</description>
        <inlineHelpText>Applicable only for GroupVolume.</inlineHelpText>
        <label>Products Based On</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Discount Item</label>
    <nameField>
        <label>Discount Item Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discount Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/REVVY__MnQuote__c.object
<CustomObject>
</CustomObject>

src/objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Product_Type__c</fullName>
        <formula>TEXT( REVVY__Catalog_Node__r.Product_Type__c )</formula>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCD_Volume_Discount_Id__c</fullName>
        <label>OCD Volume Discount Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItemSubLine__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Product_Type__c</fullName>
        <formula>TEXT( REVVY__Catalog_Node__r.Product_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/OCDSpecificDiscountCalcTest.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @group Get Price
* @group-content ../../ApexDocContent/OCDSpecificDiscountCalcTest.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

@isTest
private class OCDSpecificDiscountCalcTest {
	@testSetup static void loadData() {
		OCD_TestData.createCLTestData();
	}
    static testMethod void testSpecificDiscount() {
    	Discount__c d = [Select d.Id From Discount__c d where Name='US CC Discounts 2015' limit 1];
    	List<Discount_Item__c> dis = [Select d.Id, country__c From Discount_Item__c d where Discount__c = :d.id];
    	for(Discount_Item__c di : dis) {
    		di.Products_Based_On__c = '6842905,8301764,8329930';
    		system.debug('--------di country =' + di.country__c);
    	}
    	update dis;
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId = null;
		try{ 
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName); 
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);          
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
			for(REVVY__MnQuoteItem__c qi : qlItems) {
				if(qi.OCD_Product_Type__c == 'Consumables') {
					qi.OCD_Volume_Discount_Id__c = d.Id;
				}
			}
			
			update qlItems;
			OCDQuotePricingInfo ocdPrInfo = new OCDQuotePricingInfo();
			ocdPrInfo.qLIList = qlItems;
			ocdPrInfo.quoteHeaderObj = quoteHeaderObj;
			ocdPrInfo.qSubLIList = qlItemSublines;
			
			OCDSpecificDiscountCalc calc = new OCDSpecificDiscountCalc();
			calc.calculateProductVolumeDiscounts(ocdPrInfo);
			calc.calculateIHDisc(ocdPrInfo);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
	}
	
}