src/objects/Discount__c.object
<CustomObject>
    <description>Discount Header which should be associated to the Price Plan.</description>
    <label>Discount</label>
    <nameField>
        <label>Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Discount_Item__c.object
<CustomObject>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <picklist>
            <picklistValues>
                <fullName>Volume</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GroupVolume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GroupVolumeRBC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Discount Items</relationshipLabel>
        <relationshipName>Discount_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Discount Item</label>
    <nameField>
        <label>Discount Item Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discount Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/REVVY__MnPriceListLine__c.object
<CustomObject>
    <fields>
        <fullName>Discount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Volume Discount</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Discount__c.Level_Applied__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Discount__c</referenceTo>
        <relationshipLabel>Price List Lines</relationshipLabel>
        <relationshipName>Discount_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OCD_Product_Type__c</fullName>
        <description>to display in Pricelist lines</description>
        <formula>TEXT( REVVY__Product__r.Product_Type__c )</formula>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>Price List Line ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Service_Discount_Amount__c</fullName>
        <description>Multiple Year Discount (per year of contract)</description>
        <inlineHelpText>Multiple Year Discount (per year of contract)</inlineHelpText>
        <label>Service Discount Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Service_Discount_Max_Year__c</fullName>
        <description>Max No of years for discount (AB)</description>
        <inlineHelpText>Max No of years for discount (AB)</inlineHelpText>
        <label>Service Discount Max Year</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQiSubLineAttribute__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Attrib_Value__c</fullName>
        <label>OCD Attrib Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__ActualValue__c</fullName>
        <label>ActualValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__AttributeValue__c</fullName>
        <label>AttributeValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__CatalogAttribute__c</fullName>
        <label>CatalogAttribute</label>
        <referenceTo>REVVY__MnCatalogAttribute__c</referenceTo>
        <relationshipLabel>QiSubLineAttributes</relationshipLabel>
        <relationshipName>QiSubLineAttributes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>REVVY__QuoteItemSubLine__c</fullName>
        <label>QuoteItemSubLine</label>
        <referenceTo>REVVY__MnQuoteItemSubLine__c</referenceTo>
        <relationshipLabel>QiSubLineAttributes</relationshipLabel>
        <relationshipName>QiSubLineAttributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>equipmentName__c</fullName>
        <label>Equipment Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>serialNumber__c</fullName>
        <label>Serial Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>tradeInValue__c</fullName>
        <label>Trade-In Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <displayFormat>Q{00000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>ID</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>As Per Quote Type</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash Purchase Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_Product_Type__c</fullName>
        <formula>TEXT( REVVY__Catalog_Node__r.Product_Type__c )</formula>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCD_Trade_In_Value__c</fullName>
        <label>OCD Trade In Value</label>
        <summarizedField>REVVY__MnQuoteItemSubLine__c.OCD_Line_Trade_In_Value__c</summarizedField>
        <summaryForeignKey>REVVY__MnQuoteItemSubLine__c.REVVY__QuoteItem__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>Quote Item ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ccQty__c</fullName>
        <label>ccQty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>iaQty__c</fullName>
        <label>iaQty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItemAttribute__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__ActualValue__c</fullName>
        <label>ActualValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__AttributeValue__c</fullName>
        <label>AttributeValue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__CatalogAttribute__c</fullName>
        <label>CatalogAttribute</label>
        <referenceTo>REVVY__MnCatalogAttribute__c</referenceTo>
        <relationshipLabel>QuoteItemAttributes</relationshipLabel>
        <relationshipName>QuoteItemAttributes</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>REVVY__QuoteItem__c</fullName>
        <label>QuoteItem</label>
        <referenceTo>REVVY__MnQuoteItem__c</referenceTo>
        <relationshipLabel>QuoteItemAttributes</relationshipLabel>
        <relationshipName>QuoteItemAttributes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ccQty__c</fullName>
        <label>ccQty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>iaQty__c</fullName>
        <label>iaQty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItemSubLine__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Line_Trade_In_Value__c</fullName>
        <label>OCD Line Trade In Value</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>As Per Quote Type</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash Purchase Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_Product_Type__c</fullName>
        <formula>TEXT( REVVY__Catalog_Node__r.Product_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCD_Trade_In_Value__c</fullName>
        <description>Trade In Value</description>
        <label>Trade In Value</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Deprecated</description>
        <externalId>true</externalId>
        <inlineHelpText>Deprecated</inlineHelpText>
        <label>Deprecated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>REVVY__QuoteItem__c</fullName>
        <description>Unique ID of the line item (i.e., the quote item) in the quote.</description>
        <inlineHelpText>Unique ID of the line item (i.e., the quote item) in the quote.</inlineHelpText>
        <label>Quote Item</label>
        <referenceTo>REVVY__MnQuoteItem__c</referenceTo>
        <relationshipLabel>QuoteItemSubLine</relationshipLabel>
        <relationshipName>QuoteItemSubLine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/classes/OCDUpdatePriceDetailsTest.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @group Get Price
* @group-content ../../ApexDocContent/OCDUpdatePriceDetailsTest.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

@isTest
public with sharing class OCDUpdatePriceDetailsTest {
	@testSetup static void loadData() {
		OCD_TestData.createCLTestData();
		List<REVVY__MnCatalogAttribute__c> catalogAttrs = new List<REVVY__MnCatalogAttribute__c> {
			new REVVY__MnCatalogAttribute__c(name ='finalPrice' , REVVY__Id__c = 'finalPrice')
		};
		insert catalogAttrs;
	}
	static testMethod void uniteTest1()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId = null;
		try{ 
			Discount__c d = [Select d.Id From Discount__c d where Name='US CC Discounts 2015' limit 1];
	    	List<Discount_Item__c> dis = [Select d.Id From Discount_Item__c d where Discount__c = :d.id];
	    	for(Discount_Item__c di : dis) {
	    		di.Discount_type__c = 'Term';
	    		break;
	    	}
	    	update dis;
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName); 
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);          
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
			
			
			List<REVVY__MnQuoteItemAttribute__c> qias = new List<REVVY__MnQuoteItemAttribute__c>();
			
			for(REVVY__MnQuoteItem__c qi : qlItems) {
				if('Equipment'.equalsIgnoreCase(qi.OCD_Product_Type__c)) {
					qias.add(new REVVY__MnQuoteItemAttribute__c(REVVY__QuoteItem__c = qi.Id, REVVY__AttributeValue__c = '131', REVVY__ActualValue__c='131', ccQty__c=131,
									REVVY__CatalogAttribute__r = new REVVY__MnCatalogAttribute__c(REVVY__Id__c='finalPrice')));
					qias.add(new REVVY__MnQuoteItemAttribute__c(REVVY__QuoteItem__c = qi.Id, REVVY__AttributeValue__c = '100', REVVY__ActualValue__c='100', iaQty__c=100,
									REVVY__CatalogAttribute__r = new REVVY__MnCatalogAttribute__c(REVVY__Id__c='miscCost')));
					qias.add(new REVVY__MnQuoteItemAttribute__c(REVVY__QuoteItem__c = qi.Id, REVVY__AttributeValue__c = '100', REVVY__ActualValue__c='100', iaQty__c=100,
									REVVY__CatalogAttribute__r = new REVVY__MnCatalogAttribute__c(REVVY__Id__c='miscListPrice')));
					qias.add(new REVVY__MnQuoteItemAttribute__c(REVVY__QuoteItem__c = qi.Id, REVVY__AttributeValue__c = '100', REVVY__ActualValue__c='100', iaQty__c=100,
									REVVY__CatalogAttribute__r = new REVVY__MnCatalogAttribute__c(REVVY__Id__c='miscName')));
				}
			}
			insert qias;
			
			for(REVVY__MnQuoteItem__c quoteli : qlItems) {
				quoteli.OCD_Payment_Type__c=null;
				break;
			}
			update qlItems;
			
			
			
			List<REVVY__MnQiSubLineAttribute__c> qislas = new List<REVVY__MnQiSubLineAttribute__c>();
			for(REVVY__MnQuoteItemSubLine__c qisl : qlItemSublines) {
				qisl.OCD_Line_Trade_In_Value__c=100;
				qislas.add( new REVVY__MnQiSubLineAttribute__c(
					REVVY__CatalogAttribute__r = new REVVY__MnCatalogAttribute__c(REVVY__Id__c='Package'),
					OCD_Attrib_Value__c = '1234',
					REVVY__ActualValue__c = '1234',
					REVVY__AttributeValue__c='1234',
					REVVY__QuoteItemSubLine__c = qisl.Id,
					serialNumber__c = '1234'
					));
				qislas.add( new REVVY__MnQiSubLineAttribute__c(
					REVVY__CatalogAttribute__r = new REVVY__MnCatalogAttribute__c(REVVY__Id__c='Package'),
					OCD_Attrib_Value__c = '333',
					REVVY__ActualValue__c = '333',
					REVVY__AttributeValue__c='333',
					REVVY__QuoteItemSubLine__c = qisl.Id,
					equipmentName__c='333'
					));
				qislas.add( new REVVY__MnQiSubLineAttribute__c(
					REVVY__CatalogAttribute__r = new REVVY__MnCatalogAttribute__c(REVVY__Id__c='Package'),
					OCD_Attrib_Value__c = '34',
					REVVY__ActualValue__c = '34',
					REVVY__AttributeValue__c='34',
					REVVY__QuoteItemSubLine__c = qisl.Id,
					tradeInValue__c =34
					));
			}
			insert qislas;
			update qlItemSublines;
			List<REVVY__MnPriceListLine__c> pricelistItems = [Select r.Id From REVVY__MnPriceListLine__c r];
			for(REVVY__MnPriceListLine__c pli : pricelistItems) {
				pli.Service_Discount_Max_Year__c = 5;
				pli.Service_Discount_Amount__c = 500;
			}
			update pricelistItems;
			
			//qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);   
			//for(REVVY__MnQuoteItem__c qi : qlItems) {
			//	system.debug('-------------' + qi.OCD_Product_Type__c + '----OCD_Trade_In_Value__c------' + qi.OCD_Trade_In_Value__c);
			//}
	        OCDUpdatePriceDetails ocdY = new OCDUpdatePriceDetails();
	        test.startTest();
			ocdY.updateAllPrices(quoteHeaderObj, qlItems, false);
			ocdY.saveQuoteAsAttachments(quoteHeaderObj, qlItems, qlItemSublines, 2);
			test.stopTest();	 
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
	} //End updateAllPricesExcStrategicTest()
	
	static testMethod void uniteTest2()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId = null;
		try{ 
			
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName); 
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);          
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
	        OCDUpdatePriceDetails ocdY = new OCDUpdatePriceDetails();
			ocdY.updateVolumeAndTermDiscounts(quoteHeaderObj, new List<REVVY__MnQuoteItem__c>());	
			system.assert(ocdY.getOCDQuotePricingInfoInst() != null);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
	} //End updateAllPricesExcStrategicTest()
	
	static testMethod void uniteTest3()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId = null;
		try{ 
			
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName); 
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);          
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
	        OCDUpdatePriceDetails ocdY = new OCDUpdatePriceDetails();
			msg = ocdY.updateAllPricesExcStrategic(quoteHeaderObj, qlItems,false);
	         
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
	} //End updateAllPricesExcStrategicTest()

} //end class