src/objects/OCD_Beh_Discount_Item__c.object
<CustomObject>
    <fields>
        <fullName>Apply_To__c</fullName>
        <label>Apply To</label>
        <picklist>
            <picklistValues>
                <fullName>AllReagents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Id</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trad IH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Discount_Code__c</fullName>
        <defaultValue>&quot;Beh Disc:&quot;</defaultValue>
        <label>Discount Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <picklist>
            <picklistValues>
                <fullName>Volume</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GroupVolume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProductQtyComparison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PurchaseAmount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multifamily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AssayCount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL Volume</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>=</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt;&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;=</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Products_Applied_On__c</fullName>
        <label>Products Applied On</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_LHS__c</fullName>
        <label>Products LHS</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_RHS__c</fullName>
        <label>Products RHS</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>OCD Beh Discount Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCD Beh Discount Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OCD_Beh_DiscountItem.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @group Get Price
* @group-content ../../ApexDocContent/OCD_Beh_DiscountItem.htm 
*
* @description Store constants used by Get Price module
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

public with sharing class OCD_Beh_DiscountItem {
	/*********************************************************************************************
    * @description Constructor
    * @param OCD_Beh_Discount_Item__c di
    **********************************************************************************************/
	public OCD_Beh_DiscountItem(OCD_Beh_Discount_Item__c di) {
		discountCode = di.discount_code__c;
		discountType = di.Discount_Type__c;
		productsAppliedOn = di.Products_Applied_On__c;
		applyTo = di.Apply_To__c;
		productsLHS = OCDMNQuoteUtility.defaultString(di.Products_LHS__c);
		productsRHS = OCDMNQuoteUtility.defaultString(di.Products_RHS__c);
		operator = di.Operator__c;
	}
	/*********************************************************************************************
    * @description Constructor
    **********************************************************************************************/	
	public OCD_Beh_DiscountItem() {
		discountCode = '';
		discountType = '';
		productsAppliedOn = '';
		applyTo = '';
		productsLHS = '';
		productsRHS = '';
		operator = '';
	}
	/*********************************************************************************************
    * @description class variables
    **********************************************************************************************/
	public decimal discount {get; set;}
	public string discountCode {get; set; }
	public string discountType {get; set;}
	public string productsAppliedOn { get; set; }
	public string applyTo { get; set; }
	public string productsLHS { get; set; }
	public string productsRHS { get; set; }
	public string operator { get; set; }  
}