src/objects/OCD_Beh_Discount__c.object
<CustomObject>
    <description>Behavioural Discount Header</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <picklist>
            <picklistValues>
                <fullName>Behavioral</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Volume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>OCD Beh Discount</label>
    <nameField>
        <label>OCD Beh Discount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCD Beh Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OCD_Beh_Discount_Item__c.object
<CustomObject>
    <fields>
        <fullName>Adj_Type__c</fullName>
        <label>Adj Type</label>
        <picklist>
            <picklistValues>
                <fullName>Percent</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Amount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Markup</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Apply_To__c</fullName>
        <label>Apply To</label>
        <picklist>
            <picklistValues>
                <fullName>AllReagents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Product Id</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trad IH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Based_On__c</fullName>
        <label>Based On</label>
        <picklist>
            <picklistValues>
                <fullName>AllReagents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AllProducts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trad IH</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>CC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <defaultValue>&quot;USA&quot;</defaultValue>
        <description>To identify a country specific discount</description>
        <label>Country</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Discount_Code__c</fullName>
        <defaultValue>&quot;Beh Disc:&quot;</defaultValue>
        <label>Discount Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <picklist>
            <picklistValues>
                <fullName>Volume</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GroupVolume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProductQtyComparison</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PurchaseAmount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Multifamily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AssayCount</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CL Volume</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Id__c</fullName>
        <inlineHelpText>This should match the Criteria Group Id in the corresponding Behavior Eligibility Object.</inlineHelpText>
        <label>Group Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Adj_Amount__c</fullName>
        <label>Max Adj Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Qty__c</fullName>
        <label>Max Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Sites__c</fullName>
        <description>Maximun Site count</description>
        <label>Max Sites</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Measure__c</fullName>
        <label>Measure</label>
        <picklist>
            <picklistValues>
                <fullName>Units</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Months</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Min_Adj_Amount__c</fullName>
        <label>Min Adj Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Qty__c</fullName>
        <label>Min Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Sites__c</fullName>
        <description>Lower bound of site count</description>
        <label>Min Sites</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MultiFamilyOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>MultiFamilyOnly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OCD_Beh_Discount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCD Beh Discount</label>
        <referenceTo>OCD_Beh_Discount__c</referenceTo>
        <relationshipLabel>Discount Items</relationshipLabel>
        <relationshipName>OCD_Beh_Discount_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>=</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&lt;&gt;</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;=</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>&gt;</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Products_Applied_On__c</fullName>
        <label>Products Applied On</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_Based_On__c</fullName>
        <label>Products Based On</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_LHS__c</fullName>
        <label>Products LHS</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Products_RHS__c</fullName>
        <label>Products RHS</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Qty_to_exclude__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Applicable only to Discount Type :Volume (From the Product Volume Qualified , the numbers in this field will be excluded.If not applicable , enter zero)</inlineHelpText>
        <label>Qty to exclude</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OCD Beh Discount Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCD Beh Discount Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OCD_Beh_Eligibility__c.object
<CustomObject>
    <description>Behavioural Discount Eligibility Conditions will be stored in this Object.</description>
    <fields>
        <fullName>External_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Id__c</fullName>
        <inlineHelpText>Must be a unique String across the PL. (Generate a name with PL + Number)
This should match the Criteria Group Id in the corresponding Behavior Discount Item Object.</inlineHelpText>
        <label>Group Id</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Max_Qty__c</fullName>
        <label>Max Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Qty__c</fullName>
        <label>Min Qty</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OCD_Beh_Discount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCD Beh Discount</label>
        <referenceTo>OCD_Beh_Discount__c</referenceTo>
        <relationshipLabel>Eligibility</relationshipLabel>
        <relationshipName>OCD_Beh_Eligibilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Products_Based_On__c</fullName>
        <label>Products Based On</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Volume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName># of Sites</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ProductVolume</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>OCD Beh Eligibility</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCD Beh Eligibilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/REVVY__MnPriceList__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Beh_Discount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Behavioral Discount</label>
        <referenceTo>OCD_Beh_Discount__c</referenceTo>
        <relationshipLabel>Price Lists</relationshipLabel>
        <relationshipName>Price_Lists</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>OCD_IDN_Sites__c</fullName>
        <label>Number of Participating Sites</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OCD_Menu_Disc__c</fullName>
        <label>Menu Disc</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
</CustomObject>

src/classes/OCDBehDiscountCalcIHTest.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @group Get Price
* @group-content ../../ApexDocContent/OCDBehDiscountCalcIHTest.htm 
*
* @description The class calculates the Behaviroual discounts on the Quote
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

@isTest
private class OCDBehDiscountCalcIHTest {
@testSetup static void loadData() {
    	OCD_TestData.createIHTestData(); 
    	Id behDiscountId = [select id from OCD_Beh_Discount__c where name='US CAT Beh Discounts 2015' limit 1].Id;
		
		insert new OCD_Beh_Eligibility__c(Name='IDN', GROUP_ID__C = 'IDN', TYPE__C='None', OCD_BEH_DISCOUNT__C = behDiscountId, EXTERNAL_ID__C='IDN-1');
		insert new List<OCD_Beh_Discount_Item__c> {
			new OCD_Beh_Discount_Item__c(
				NAME='SiteCommitment',
				ADJ_TYPE__C='Percent',
				APPLY_TO__C='',
				BASED_ON__C='CAT',
				DISCOUNT_CODE__C='Site Commitment:',
				DISCOUNT_TYPE__C='SiteCommitment',
				OCD_BEH_Discount__c = behDiscountId,
				GROUP_ID__C='IDN',
				MAX_ADJ_AMOUNT__C=3,
				MAX_QTY__C=74,
				MIN_ADJ_AMOUNT__C=3,
				MIN_QTY__C=65,
				MULTIFAMILYONLY__C=TRUE,
				OPERATOR__C='',
				PRODUCTS_APPLIED_ON__C='MTS080515,MTS081115,MTS080024,MTS080210,MTS080310,MTS080212,MTS080312,MTS080017,MTS080014,MTS080015,MTS080016,MTS081221,MTS081001,716360,716760,719210,719310,719810,Z498,H9000,711830,716540,H360,713080,714080,713180,716530,719610,715150,Z488,6901934,6901935,6901939,719000,6902096,719100,6902525,715130,714180,719510,721830,718380,718280,715850,719520,715950,725230,721380,715280,721480,721130,716080,716980,715530,721030,723030,711520,711320,711220,719410,717380,715480,715380,6902526,712380,718100,718300,716700,716300,716000,716910',
				PRODUCTS_BASED_ON__C='',
				PRODUCTS_LHS__C='',
				PRODUCTS_RHS__C='',
				EXTERNAL_ID__C='IDN_SITE_1',
				QTY_TO_EXCLUDE__C=0,
				COUNTRY__C='US',
				MIN_SITES__C=4,
				MAX_SITES__C=99999),
			new OCD_Beh_Discount_Item__c(
				NAME='SiteCommitment',
				ADJ_TYPE__C='Percent',
				APPLY_TO__C='',
				BASED_ON__C='CAT',
				DISCOUNT_CODE__C='Site Commitment:',
				DISCOUNT_TYPE__C='SiteCommitment',
				GROUP_ID__C='IDN',
				MAX_ADJ_AMOUNT__C=4.5,
				MAX_QTY__C=89,
				MIN_ADJ_AMOUNT__C=4.5,
				MIN_QTY__C=75,
				OCD_BEH_Discount__c = behDiscountId,
				MULTIFAMILYONLY__C=TRUE,
				OPERATOR__C='',
				PRODUCTS_APPLIED_ON__C='MTS080515,MTS081115,MTS080024,MTS080210,MTS080310,MTS080212,MTS080312,MTS080017,MTS080014,MTS080015,MTS080016,MTS081221,MTS081001,716360,716760,719210,719310,719810,Z498,H9000,711830,716540,H360,713080,714080,713180,716530,719610,715150,Z488,6901934,6901935,6901939,719000,6902096,719100,6902525,715130,714180,719510,721830,718380,718280,715850,719520,715950,725230,721380,715280,721480,721130,716080,716980,715530,721030,723030,711520,711320,711220,719410,717380,715480,715380,6902526,712380,718100,718300,716700,716300,716000,716910',
				PRODUCTS_BASED_ON__C='',
				PRODUCTS_LHS__C='',
				PRODUCTS_RHS__C='',
				EXTERNAL_ID__C='IDN_SITE_2',
				QTY_TO_EXCLUDE__C=0,
				COUNTRY__C='US',
				MIN_SITES__C=4,
				MAX_SITES__C=99999),
			new OCD_Beh_Discount_Item__c(
				NAME='SiteCommitment',
				ADJ_TYPE__C='Percent',
				APPLY_TO__C='',
				BASED_ON__C='CAT',
				DISCOUNT_CODE__C='Site Commitment:',
				DISCOUNT_TYPE__C='SiteCommitment',
				GROUP_ID__C='IDN',
				MAX_ADJ_AMOUNT__C=5,
				MAX_QTY__C=1000000000,
				MIN_ADJ_AMOUNT__C=5,
				MIN_QTY__C=90,
				OCD_BEH_Discount__c = behDiscountId,
				MULTIFAMILYONLY__C=TRUE,
				OPERATOR__C='',
				PRODUCTS_APPLIED_ON__C='MTS080515,MTS081115,MTS080024,MTS080210,MTS080310,MTS080212,MTS080312,MTS080017,MTS080014,MTS080015,MTS080016,MTS081221,MTS081001,716360,716760,719210,719310,719810,Z498,H9000,711830,716540,H360,713080,714080,713180,716530,719610,715150,Z488,6901934,6901935,6901939,719000,6902096,719100,6902525,715130,714180,719510,721830,718380,718280,715850,719520,715950,725230,721380,715280,721480,721130,716080,716980,715530,721030,723030,711520,711320,711220,719410,717380,715480,715380,6902526,712380,718100,718300,716700,716300,716000,716910',
				PRODUCTS_BASED_ON__C='',
				PRODUCTS_LHS__C='',
				PRODUCTS_RHS__C='',
				EXTERNAL_ID__C='IDN_SITE_3',
				QTY_TO_EXCLUDE__C=0,
				COUNTRY__C='US',
				MIN_SITES__C=4,
				MAX_SITES__C=99999)	
		};
		insert new List<OCD_Beh_Discount_Item__c> {
			new OCD_Beh_Discount_Item__c(
				NAME='Grt',
				ADJ_TYPE__C='Percent',
				APPLY_TO__C='',
				BASED_ON__C='Trad IH',
				DISCOUNT_CODE__C='Menu Discount:',
				DISCOUNT_TYPE__C='IDNProductQtyComparison',
				GROUP_ID__C='IDN',
				MAX_ADJ_AMOUNT__C=3,
				MAX_QTY__C=60,
				MIN_ADJ_AMOUNT__C=0,
				OCD_BEH_Discount__c = behDiscountId,
				MIN_QTY__C=40,
				MULTIFAMILYONLY__C=FALSE,
				OPERATOR__C='>=',
				PRODUCTS_APPLIED_ON__C='MTS080515,MTS081115,MTS080024,MTS080210,MTS080310,MTS080212,MTS080312,MTS080017,MTS080014,MTS080015,MTS080016,MTS081221,MTS081001,716360,716760,719210,719310,719810,Z498,H9000,711830,716540,H360,713080,714080,713180,716530,719610,715150,Z488,6901934,6901935,6901939,719000,6902096,719100,6902525,715130,714180,719510,721830,718380,718280,715850,719520,715950,725230,721380,715280,721480,721130,716080,716980,715530,721030,723030,711520,711320,711220,719410,717380,715480,715380,6902526,712380,718100,718300,716700,716300,716000,716910',
				PRODUCTS_BASED_ON__C='MTS08505,MTS081115',
				PRODUCTS_LHS__C='MTS080515,MTS081115,MTS080014,MTS080015,MTS080016,MTS080017',
				PRODUCTS_RHS__C='',
				EXTERNAL_ID__C='IDN_MENU_2',
				QTY_TO_EXCLUDE__C=0,
				COUNTRY__C='US',
				MIN_SITES__C=4,
				MAX_SITES__C=99999),
			new OCD_Beh_Discount_Item__c(
				NAME='Grt',
				ADJ_TYPE__C='Percent',
				APPLY_TO__C='',
				BASED_ON__C='Trad IH',
				DISCOUNT_CODE__C='Menu Discount:',
				DISCOUNT_TYPE__C='IDNProductQtyComparison',
				GROUP_ID__C='IDN',
				MAX_ADJ_AMOUNT__C=5,
				MAX_QTY__C=75,
				MIN_ADJ_AMOUNT__C=3.5,
				OCD_BEH_Discount__c = behDiscountId,
				MIN_QTY__C=61,
				MULTIFAMILYONLY__C=FALSE,
				OPERATOR__C='>=',
				PRODUCTS_APPLIED_ON__C='MTS080515,MTS081115,MTS080024,MTS080210,MTS080310,MTS080212,MTS080312,MTS080017,MTS080014,MTS080015,MTS080016,MTS081221,MTS081001,716360,716760,719210,719310,719810,Z498,H9000,711830,716540,H360,713080,714080,713180,716530,719610,715150,Z488,6901934,6901935,6901939,719000,6902096,719100,6902525,715130,714180,719510,721830,718380,718280,715850,719520,715950,725230,721380,715280,721480,721130,716080,716980,715530,721030,723030,711520,711320,711220,719410,717380,715480,715380,6902526,712380,718100,718300,716700,716300,716000,716910',
				PRODUCTS_BASED_ON__C='MTS08505,MTS081115',
				PRODUCTS_LHS__C='MTS080515,MTS081115,MTS080014,MTS080015,MTS080016,MTS080017',
				PRODUCTS_RHS__C='',
				EXTERNAL_ID__C='IDN_MENU_3',
				QTY_TO_EXCLUDE__C=0,
				COUNTRY__C='US',
				MIN_SITES__C=4,
				MAX_SITES__C=99999),
			new OCD_Beh_Discount_Item__c(
				NAME='Grt',
				ADJ_TYPE__C='Percent',
				APPLY_TO__C='',
				BASED_ON__C='Trad IH',
				DISCOUNT_CODE__C='Menu Discount:',
				DISCOUNT_TYPE__C='IDNProductQtyComparison',
				GROUP_ID__C='IDN',
				MAX_ADJ_AMOUNT__C=8,
				MAX_QTY__C=100,
				MIN_ADJ_AMOUNT__C=5.5,
				OCD_BEH_Discount__c = behDiscountId,
				MIN_QTY__C=76,
				MULTIFAMILYONLY__C=FALSE,
				OPERATOR__C='>=',
				PRODUCTS_APPLIED_ON__C='MTS080515,MTS081115,MTS080024,MTS080210,MTS080310,MTS080212,MTS080312,MTS080017,MTS080014,MTS080015,MTS080016,MTS081221,MTS081001,716360,716760,719210,719310,719810,Z498,H9000,711830,716540,H360,713080,714080,713180,716530,719610,715150,Z488,6901934,6901935,6901939,719000,6902096,719100,6902525,715130,714180,719510,721830,718380,718280,715850,719520,715950,725230,721380,715280,721480,721130,716080,716980,715530,721030,723030,711520,711320,711220,719410,717380,715480,715380,6902526,712380,718100,718300,716700,716300,716000,716910',
				PRODUCTS_BASED_ON__C='MTS08505,MTS081115',
				PRODUCTS_LHS__C='MTS080515,MTS081115,MTS080014,MTS080015,MTS080016,MTS080017',
				PRODUCTS_RHS__C='',
				EXTERNAL_ID__C='IDN_MENU_4',
				QTY_TO_EXCLUDE__C=0,
				COUNTRY__C='US',
				MIN_SITES__C=4,
				MAX_SITES__C=99999)	
		};
	}
	
	
	
    static testMethod void testApplySiteIDNMenuDisc()
	{
		String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId=null;
		
		List<OCD_Beh_Discount_Item__c> discItems = [Select o.Qty_to_exclude__c, o.Products_RHS__c, o.Products_LHS__c, 
	        			o.Products_Based_On__c, o.Products_Applied_On__c, o.Operator__c, o.Name, o.MultiFamilyOnly__c, 
	        			o.Min_Sites__c, o.Min_Qty__c, o.Min_Adj_Amount__c, o.Measure__c, o.Max_Sites__c, o.Max_Qty__c, 
	        			o.Max_Adj_Amount__c, o.Group_Id__c, o.External_ID__c, o.Discount_Type__c, 
	        			o.Discount_Code__c, o.Description__c, o.Country__c, o.Based_On__c, o.Apply_To__c 
	        			From OCD_Beh_Discount_Item__c o where DISCOUNT_TYPE__C = 'IDNProductQtyComparison'];
		try{
			
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName); 
			quoteHeaderObj.RecordTypeId = Schema.SObjectType.REVVY__MnQuote__c.getRecordTypeInfosByName().get('IDN').getRecordTypeId();
			quoteHeaderObj.OCD_Menu_Disc__c = 0;
			update quoteHeaderObj;
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);  
			OCDQuotePriceLookup.isIDNQuote = true;   
			OCDQuotePriceLookup.IDNSiteCount=1;     
	        OCDBehDiscountCalc calc = new OCDBehDiscountCalc();
	        OCDQuotePricingInfo ocdPrInfo = new OCDQuotePricingInfo();
			ocdPrInfo.qLIList = qlItems;
			ocdPrInfo.quoteHeaderObj = quoteHeaderObj;
	        calc.percentItemsPurchased = 50;
	        calc.setCurrentQuoteLineItems(qlItems);
	        calc.setCurrentQuote(quoteHeaderObj);
	        calc.applySiteIDNMenuDisc(discItems);
	        calc.updateBehDiscounts(ocdPrInfo, quoteHeaderObj, qlItems);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
	} //End updateAllPricesExcStrategicTest()
	
	static testMethod void testApplySiteCommitmentDisc()
	{
		String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId=null;
		
		
		List<OCD_Beh_Discount_Item__c> discItems = [Select o.Qty_to_exclude__c, o.Products_RHS__c, o.Products_LHS__c, 
	        			o.Products_Based_On__c, o.Products_Applied_On__c, o.Operator__c, o.Name, o.MultiFamilyOnly__c, 
	        			o.Min_Sites__c, o.Min_Qty__c, o.Min_Adj_Amount__c, o.Measure__c, o.Max_Sites__c, o.Max_Qty__c, 
	        			o.Max_Adj_Amount__c, o.Group_Id__c, o.External_ID__c, o.Discount_Type__c, OCD_BEH_Discount__c,
	        			o.Discount_Code__c, o.Description__c, o.Country__c, o.Based_On__c, o.Apply_To__c 
	        			From OCD_Beh_Discount_Item__c o where DISCOUNT_TYPE__C = 'SiteCommitment'];
		try{
			
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName); 
			
			quoteHeaderObj.RecordTypeId = Schema.SObjectType.REVVY__MnQuote__c.getRecordTypeInfosByName().get('IDN').getRecordTypeId();
			quoteHeaderObj.OCD_IDN_Sites__c = 1;
			Id behDiscountId = [select id from OCD_Beh_Discount__c where name='US CAT Beh Discounts 2015' limit 1].Id;
			update new REVVY__MnPriceList__c(Id = quoteHeaderObj.OCD_CAT_Price_List__c, OCD_Beh_Discount__c = behDiscountId );
			
			update quoteHeaderObj;
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);  
			OCDQuotePricingInfo ocdPrInfo = new OCDQuotePricingInfo();
			ocdPrInfo.qLIList = qlItems;
			ocdPrInfo.quoteHeaderObj = quoteHeaderObj;
			
			OCDQuotePriceLookup.isIDNQuote = true;       
			OCDQuotePriceLookup.IDNSiteCount = 1;     
	        OCDBehDiscountCalc calc = new OCDBehDiscountCalc();
	        calc.percentContracted = 70;
	        calc.setCurrentQuoteLineItems(qlItems);
	        calc.setCurrentQuote(quoteHeaderObj);
	        calc.applySiteCommitmentDisc(discItems);
	        calc.updateBehDiscounts(ocdPrInfo, quoteHeaderObj, qlItems);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
	} //End updateAllPricesExcStrategicTest()
	
	static testMethod void testApplyPurchaseAmtDisc()
	{
		String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId = null;
		try{
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName); 
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);          
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
	        OCDQuotePricingInfo ocdPrInfo = new OCDQuotePricingInfo();
			ocdPrInfo.qLIList = qlItems;
			ocdPrInfo.quoteHeaderObj = quoteHeaderObj;
			ocdPrInfo.qSubLIList = qlItemSublines;
			ocdPrInfo.isIHQuote = true;
			
			OCDBehDiscountCalc ocdY = new OCDBehDiscountCalc();
			OCDMNQuoteUtility.isDistributorQuote = false;
			ocdPrInfo = ocdY.updateBehDiscounts(ocdPrInfo, quoteHeaderObj, qlItems);
			
			
	         OCD_Beh_Discount_Item__c di = new OCD_Beh_Discount_Item__c();
	         di.ADJ_TYPE__C = 'Percent';
	         di.APPLY_TO__C = 'AllReagents';
	         di.DISCOUNT_CODE__C='CommittedVolume::';
	         //di.DISCOUNT_TYPE__C='';
	         //di.GROUP_ID__C = '';
	         di.MAX_ADJ_AMOUNT__C = 5;
	         //di.MAX_QTY__C=0;
	         di.MIN_ADJ_AMOUNT__C= 2;
	         //di.Qty_to_exclude__c = 20;
	         di.Based_On__c = 'CC';
	         di.MultiFamilyOnly__c = true;
	         di.Max_Qty__c = 500;
	         di.MIN_QTY__C = 0;
	         ocdPrInfo.isIHQuote = true;
	         ocdY.setQuotePricingInfo(ocdPrInfo);
	         ocdY.applyPurchaseAmtDisc(new List <OCD_Beh_Discount_Item__c>{di});
	         
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
	} //End updateAllPricesExcStrategicTest()
	
	static testMethod void testApplyMultiFamilyDisc()
	{
		String quoteName = 'IH Test Case 9';
		String  msg ;
		String quoteId = null;
		try{
			OCDQuotePricingInfo pInfo = new OCDQuotePricingInfo();
			pInfo.isIHQuote = false;
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName); 
			quoteHeaderObj.MultiFamily__c = true;
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);          
	         OCDBehDiscountCalc calc = new OCDBehDiscountCalc();
	         calc.setCurrentQuoteLineItems(qlItems);
	         calc.setCurrentQuote(quoteHeaderObj);
	         calc.setQuotePricingInfo(pInfo);
	         OCD_Beh_Discount_Item__c di = new OCD_Beh_Discount_Item__c();
	         di.ADJ_TYPE__C = 'Percent';
	         di.APPLY_TO__C = 'AllReagents';
	         di.DISCOUNT_CODE__C='Multifamily Disc:';
	         //di.DISCOUNT_TYPE__C='';
	         //di.GROUP_ID__C = '';
	         di.MAX_ADJ_AMOUNT__C = 5;
	         //di.MAX_QTY__C=0;
	         di.MIN_ADJ_AMOUNT__C= 2;
	         //di.Qty_to_exclude__c = 20;
	         di.Based_On__c = 'CAT';
	         //di.Min_Qty__c = 500;
	         //di.MIN_QTY__C = 0;
	         OCDMNQuoteUtility.isDistributorQuote = false;
	         calc.applyMultiFamilyDisc(di);
	         
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
	} //End updateAllPricesExcStrategicTest()
}