src/objects/OCD_Deal_Assessment__c.object
<CustomObject>
    <description>Deal Assessment Summary</description>
    <fields>
        <fullName>Green_Reagent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Green Reagent</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Green__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Green</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Overall_GP_Color__c</fullName>
        <formula>IF( (Overall_GP__c *100) &gt;= Green__c ,&quot;panel-green&quot;, 
IF( (Overall_GP__c * 100) &gt;=  Yellow__c ,&quot;panel-yellow&quot;, &quot;panel-red&quot;))</formula>
        <label>Overall GP Color</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Overall_GP__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Overall GP%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Reagent_GP_Color__c</fullName>
        <formula>IF( (Reagents_GP__c * 100) &gt; Green_Reagent__c ,&quot;panel-green&quot;, 
IF( (Reagents_GP__c * 100) &gt;=  Yellow_Reagent__c ,&quot;panel-yellow&quot;, &quot;panel-red&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reagent GP Color</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reagents_GP__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reagents GP%</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Red_Reagent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Red Reagent</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Red__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Red</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yellow_Reagent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Yellow Reagent</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Yellow__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Yellow</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Financial Assessment</label>
    <nameField>
        <label>Deal Assessment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OCD_DAIndicatorController.cls
/**
* @author Indra Lugina
* @date 10/10/2016 
*
* @group FinancialAssessment
* @group-content ../../ApexDocContent/OCD_DAIndicatorController.htm 
*
* @description Financial Assement Indicator Display Controller
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Indra Lugina        10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

public class OCD_DAIndicatorController {


    /*********************************************************************************************
    * @description class variables
    **********************************************************************************************/
    public String sId {get;set;}
	public String syellow {get;set;}
	public String sgreen {get;set;}
	public String svalue {get;set;}
	public Boolean bIEBrowser {get;set;}
	public String userAgent {get;set;}
	public String tempGaugeOVGPColor {get;set;}
	public String tempGaugeRGPColor {get;set;}
	
    /*********************************************************************************************
    * @description constructor
    * @param ApexPages.StandardController controller
    **********************************************************************************************/
    public OCD_DAIndicatorController(ApexPages.StandardController controller){
        sId = controller.getRecord().Id;
        tempGaugeOVGPColor=tempGaugeRGPColor='tempGaugered';
    	syellow='35';
    	sgreen='70';
    	svalue='0';    	
    }

    /*********************************************************************************************
    * @description Initialize
    **********************************************************************************************/
	public void init() {
    	for(OCD_Deal_Assessment__c da: [Select Name, Overall_GP__c, Red__c, Yellow__c, Green__c, Reagents_GP__c, Overall_GP_Color__c, Reagent_GP_Color__c
                                              From OCD_Deal_Assessment__c 
                                             where Id =:sId]) {
    		Decimal d = 0; //Math.random() * 30;    		
    		syellow = String.valueOf(intValue(da.Yellow__c) - d);
    		sgreen = String.valueOf(intValue(da.Green__c) - d);
    		svalue = String.valueOf(intValue(da.Overall_GP__c) - d);
    		tempGaugeOVGPColor= 'tempGauge'+da.Overall_GP_Color__c.replaceAll('panel-','').toLowerCase();
    		tempGaugeRGPColor= 'tempGauge'+da.Reagent_GP_Color__c.replaceAll('panel-','').toLowerCase();
			userAgent=ApexPages.currentPage().getHeaders().get('USER-AGENT');
    		
    	}
		 	
	}

    /*********************************************************************************************
    * @description Initialize
    **********************************************************************************************/
	public void initReagent() {
    	for(OCD_Deal_Assessment__c da: [Select Name, Overall_GP__c, Red_Reagent__c, Yellow_Reagent__c, Green_Reagent__c, Reagents_GP__c, Overall_GP_Color__c, Reagent_GP_Color__c
                                              From OCD_Deal_Assessment__c 
                                             where Id =:sId]) {
    		Decimal d = 0; //Math.random() * 30;    		
    		syellow = String.valueOf(Integer.valueOf(da.Yellow_Reagent__c) - d);
    		sgreen = String.valueOf(Integer.valueOf(da.Green_Reagent__c) - d);
    		svalue = String.valueOf(Integer.valueOf(da.Reagents_GP__c) - d);
    		tempGaugeOVGPColor= 'tempGauge'+da.Overall_GP_Color__c.replaceAll('panel-','').toLowerCase();
    		tempGaugeRGPColor= 'tempGauge'+da.Reagent_GP_Color__c.replaceAll('panel-','').toLowerCase();
			userAgent=ApexPages.currentPage().getHeaders().get('USER-AGENT');
    	}
		 	
	}

    /*********************************************************************************************
    * @description Convert to Integer Value 
    * @return Integer
    **********************************************************************************************/
	public Integer intValue(Decimal d) {
		Integer result = 0;
		if(d!=null && d >0) {
			result = Integer.valueOf(d);
		} 
		return result;
	}
}