src/objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Status__c</fullName>
        <description>Where the quote is in the sales cycle. The status can be draft, ready, submitted, or ordered.</description>
        <inlineHelpText>Where the quote is in the sales cycle. The status can be draft, ready, submitted, or ordered.</inlineHelpText>
        <label>Actual Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cloning in progress...</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Creating lines in progress...</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Draft in progress...</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Importing Quote Lines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDN_Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDN_Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/classes/OCD_ProductExclusionPluginTest.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @group Product Exclusion
* @group-content ../../ApexDocContent/OCD_ProductExclusionPluginTest.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/


@isTest
private class OCD_ProductExclusionPluginTest {
    @testSetup static void loadData() {
		OCD_TestData.createCLTestData();
	}
    static testMethod void myUnitTest() {
        String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId = null;
		try{ 
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName); 
			quoteHeaderObj.revvy__status__c='Draft';
			update quoteHeaderObj;
            Map<String,Object> inputParams = new Map<String,Object>{
               'objectId' => quoteHeaderObj.Id,
               'ExProductIds' => new Set<Id>(),
               'ExCategoryIds' => new Set<Id>()
            };
        	Test.startTest();
        	OCD_ProductExclusionPlugin plugin = new OCD_ProductExclusionPlugin();
            plugin.isFullOverride();
            plugin.getExcludedProdsAndCategory(inputParams);
        	Test.stopTest();
        	//controller.returnToQuote();
        	//controller.ReadFile();
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
        
        
    }
    
}