src/objects/REVVY__MnCatalogNode__c.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Reagent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accessory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warranty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade-In</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Overridden_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Final Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Product_Type__c</fullName>
        <formula>TEXT( REVVY__Catalog_Node__r.Product_Type__c )</formula>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__Catalog_Node__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Unique ID of the product associated with this quote item.</description>
        <inlineHelpText>Unique ID of the product associated with this quote item.</inlineHelpText>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>REVVY__MnCatalogNode__c.REVVY__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnCatalogNode__c.REVVY__Type__c</field>
                <operation>equals</operation>
                <value>Bundle</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>REVVY__MnCatalogNode__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>QuoteItems</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>Quote Item ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>REVVY__Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Revvy Quoted Products</relationshipLabel>
        <relationshipName>QuoteItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Price__c</fullName>
        <description>List price of product for this quote.</description>
        <inlineHelpText>List price of product for this quote.</inlineHelpText>
        <label>List Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVVY__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of units.</description>
        <inlineHelpText>Number of units.</inlineHelpText>
        <label>Qty</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REVVY__Quote__c</fullName>
        <description>Unique ID of the quote that this quote item belongs to.</description>
        <inlineHelpText>Unique ID of the quote that this quote item belongs to.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>REVVY__MnQuote__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>QuoteItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItemSubLine__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Overridden_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Overridden Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Product_Type__c</fullName>
        <formula>TEXT( REVVY__Catalog_Node__r.Product_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>Product Type of Product. Used in Roll Up formulae.</description>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__Catalog_Node__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Unique Salesforce ID for the product that this price list line refers to.</description>
        <inlineHelpText>Unique Salesforce ID for the product that this price list line refers to.</inlineHelpText>
        <label>Product</label>
        <referenceTo>REVVY__MnCatalogNode__c</referenceTo>
        <relationshipLabel>QuoteItemSubLine</relationshipLabel>
        <relationshipName>QuoteItemSubLine</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Deprecated</description>
        <externalId>true</externalId>
        <inlineHelpText>Deprecated</inlineHelpText>
        <label>Deprecated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>REVVY__Price__c</fullName>
        <description>List price of product.</description>
        <inlineHelpText>List price of product.</inlineHelpText>
        <label>List Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVVY__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Quantity of products.</description>
        <inlineHelpText>Quantity of products.</inlineHelpText>
        <label>Qty</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REVVY__QuoteItem__c</fullName>
        <description>Unique ID of the line item (i.e., the quote item) in the quote.</description>
        <inlineHelpText>Unique ID of the line item (i.e., the quote item) in the quote.</inlineHelpText>
        <label>Quote Item</label>
        <referenceTo>REVVY__MnQuoteItem__c</referenceTo>
        <relationshipLabel>QuoteItemSubLine</relationshipLabel>
        <relationshipName>QuoteItemSubLine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/classes/OCD_QuoteProposalController.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @group Quote Proposal
* @group-content ../../ApexDocContent/OCD_QuoteProposalController.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

public class OCD_QuoteProposalController {
	/*********************************************************************************************
    * @description class variables
    **********************************************************************************************/
	public String quoteId {get;set;}
    /*********************************************************************************************
    * @description Constructor
    * @param ApexPages.StandardController controller
    **********************************************************************************************/
    public OCD_QuoteProposalController(ApexPages.StandardController controller) {
		quoteId = controller.getId();     
    }
    /*********************************************************************************************
    * @description Initializer
    * @return PageReference
    **********************************************************************************************/
	public PageReference init() {
		 createProposal();
		 PageReference pg = new PageReference('/apex/REVVY__PMnQuoteLifeCycleCtrl?action=AssembleProposal&quoteId='+quoteId);
		 pg.setRedirect(true);
		 
		return pg;
	}
    /*********************************************************************************************
    * @description Create Proposal
    * @return void
    **********************************************************************************************/	
	public void createProposal() {
		if(!String.isEmpty(quoteId)) {
			delete [Select Id From OCD_Quote_Proposal__c where Revvy_Quote__c = :quoteId];

			List<OCD_Quote_Proposal__c> qpList = new List<OCD_Quote_Proposal__c>();
				 
		    Map<String, Schema.SObjectField> fieldsMap = Schema.SobjectType.REVVY__MnQuoteItem__c.fields.getMap();
		    String sfields = OCDMNQuoteUtility.getObjectFields(fieldsMap) + ' , REVVY__Opportunity__r.closedate, REVVY__Catalog_Node__r.Name, REVVY__Catalog_Node__r.REVVY__Id__c ';
		    sfields += ' , (Select REVVY__Price__c, OCD_Overridden_Price__c, Name, REVVY__Catalog_Node__c, REVVY__Catalog_Node__r.Name, REVVY__Catalog_Node__r.REVVY__Id__c, REVVY__Quantity__c, OCD_Product_Type__c From REVVY__QuoteItemSubLine__r ) ';
		    String criteria = ' where REVVY__Quote__c = :quoteId';
		    String query = OCDMNQuoteUtility.buildSQLStatement(sfields, 'REVVY__MnQuoteItem__c', criteria);
			for(REVVY__MnQuoteItem__c qi:Database.query(query)) {
				OCD_Quote_Proposal__c qp = new OCD_Quote_Proposal__c(Revvy_Quote__c=quoteId
						                                             ,Quote_Item__c=qi.Id
						                                             ,Product_Type__c=qi.OCD_Product_Type__c);
				Decimal totalAmount = 0;
				List<OCD_Quote_Proposal__c> qpslIncludeList = new List<OCD_Quote_Proposal__c>();
				List<OCD_Quote_Proposal__c> qpslExcludeList = new List<OCD_Quote_Proposal__c>();
				if(qi.REVVY__QuoteItemSubLine__r!=null && qi.REVVY__QuoteItemSubLine__r.size()>0) {
					for(REVVY__MnQuoteItemSubLine__c qisl:qi.REVVY__QuoteItemSubLine__r) {
						if(qisl.REVVY__Price__c > 0) {
							qpslExcludeList.add(new OCD_Quote_Proposal__c(Revvy_Quote__c=quoteId
							                                             ,Quote_Item__c=qi.Id
							                                             ,Quote_Item_Sub_Line__c=qisl.Id
							                                             ,Product_Type__c=qisl.OCD_Product_Type__c));
						} else {
							qpslIncludeList.add(new OCD_Quote_Proposal__c(Revvy_Quote__c=quoteId
							                                             ,Quote_Item__c=qi.Id
							                                             ,Quote_Item_Sub_Line__c=qisl.Id
							                                             ,Product_Type__c=qi.OCD_Product_Type__c));
							totalAmount += OCDMNQuoteUtility.defaultDecimal(qisl.OCD_Overridden_Price__c) * OCDMNQuoteUtility.defaultDecimal(qisl.REVVY__Quantity__c);
						}
					}
				}
				qp.Total_Sub_Line__c = totalAmount;
				qpList.add(qp);
				qpList.addAll(qpslIncludeList);
				qpList.addAll(qpslExcludeList);
			}
			
			insert qpList;
		}
	}
}