src/objects/REVVY__MnCatalogNode__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Configurable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines product as a configurable product.</description>
        <inlineHelpText>Defines product as a configurable product. Checking this box means that the product is configurable.</inlineHelpText>
        <label>Configurable</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>IDN_Type__c</fullName>
        <label>IDN Type</label>
        <picklist>
            <picklistValues>
                <fullName>All in One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Base Reagent Price</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_Billing_ISO_Country_Code__c</fullName>
        <label>Billing ISO Country Code</label>
        <picklist>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_CC_Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Price Plan</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3 AND 4) OR 5</booleanFilter>
            <errorMessage>Invalid CC Price Plan. Please select valid CC Price Plan</errorMessage>
            <filterItems>
                <field>REVVY__MnPriceList__c.LOB__c</field>
                <operation>equals</operation>
                <value>CC</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnPriceList__c.Is_Valid__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnPriceList__c.Country_applicability__c</field>
                <operation>equals</operation>
                <valueField>$Source.OCD_Billing_ISO_Country_Code__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.REVVY__Status__c</field>
                <operation>equals</operation>
                <value>Cloning in progress..., Creating lines in progress..., Draft, Draft in progress..., Importing Quote Lines, Ready, Submitted, IDN_Completed, IDN_Error</value>
            </filterItems>
            <filterItems>
                <field>$Source.REVVY__Status__c</field>
                <operation>equals</operation>
                <value>Ordered</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>REVVY__MnPriceList__c</referenceTo>
        <relationshipLabel>Revvy Quotes (CC Price Plan)</relationshipLabel>
        <relationshipName>CC_Price_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OCD_IA_Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IA Price Plan</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3 AND 4) OR 5</booleanFilter>
            <errorMessage>Invalid IA Price Plan. Please select valid IA Price Plan</errorMessage>
            <filterItems>
                <field>REVVY__MnPriceList__c.LOB__c</field>
                <operation>equals</operation>
                <value>IA</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnPriceList__c.Is_Valid__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnPriceList__c.Country_applicability__c</field>
                <operation>equals</operation>
                <valueField>$Source.OCD_Billing_ISO_Country_Code__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.REVVY__Status__c</field>
                <operation>equals</operation>
                <value>Cloning in progress..., Creating lines in progress..., Draft, Draft in progress..., Importing Quote Lines, Ready, Submitted, IDN_Completed, IDN_Error</value>
            </filterItems>
            <filterItems>
                <field>$Source.REVVY__Status__c</field>
                <operation>equals</operation>
                <value>Ordered</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>REVVY__MnPriceList__c</referenceTo>
        <relationshipLabel>Revvy Quotes (IA Price Plan)</relationshipLabel>
        <relationshipName>IA_Price_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Unique ID of the account that is associated with the quote.</description>
        <inlineHelpText>Unique ID of the account that is associated with the quote.</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <errorMessage>You should assign only group accounts to group quotes</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Group Quote</value>
            </filterItems>
            <filterItems>
                <field>Account.REVVY__MnIsGroupAccount__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Group Quote</value>
            </filterItems>
            <filterItems>
                <field>Account.REVVY__MnIsGroupAccount__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Revvy Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Expiration_Date__c</fullName>
        <defaultValue>NOW() +   VALUE( $Label.REVVY__MnDefaultQuoteExpirationDays )</defaultValue>
        <description>Date when the quote expires.</description>
        <inlineHelpText>Date when the quote expires.</inlineHelpText>
        <label>Expires</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ship_To_Customer_Number_for_Quote__c</fullName>
        <description>The Ship to Customer for the quote. This is one of the number in the Ship-To Customer Numbers field on the Account</description>
        <inlineHelpText>Enter Ship To Customer number for quote  from the list of customer numbers in the Ship-To Customer Numbers on the Account</inlineHelpText>
        <label>Enter Ship To Customer Number for Quote</label>
        <length>8</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Price__c</fullName>
        <description>List price of product for this quote.</description>
        <inlineHelpText>List price of product for this quote.</inlineHelpText>
        <label>List Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVVY__Quote__c</fullName>
        <description>Unique ID of the quote that this quote item belongs to.</description>
        <inlineHelpText>Unique ID of the quote that this quote item belongs to.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>REVVY__MnQuote__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>QuoteItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItemSubLine__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Price__c</fullName>
        <description>List price of product.</description>
        <inlineHelpText>List price of product.</inlineHelpText>
        <label>List Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVVY__QuoteItem__c</fullName>
        <description>Unique ID of the line item (i.e., the quote item) in the quote.</description>
        <inlineHelpText>Unique ID of the line item (i.e., the quote item) in the quote.</inlineHelpText>
        <label>Quote Item</label>
        <referenceTo>REVVY__MnQuoteItem__c</referenceTo>
        <relationshipLabel>QuoteItemSubLine</relationshipLabel>
        <relationshipName>QuoteItemSubLine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/classes/OCD_IDNBaseReagentBatchableTest.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @deprecated
*
* @group Network Quote
* @group-content ../../ApexDocContent/OCD_IDNBaseReagentBatchableTest.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

@isTest
private class OCD_IDNBaseReagentBatchableTest {

   @testSetup static void loadData() {
		OCD_TestData.createCLTestData(); 
	}
    static testMethod void myUnitTest() {
        String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{			
			list<REVVY__MnCatalogNode__c> ps = [Select r.Id From REVVY__MnCatalogNode__c r];
			for(REVVY__MnCatalogNode__c c : ps) {
				c.revvy__configurable__c = false;
			}
			update ps;
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, REVVY__Account__c, REVVY__Account__r.Id, name, OCD_CC_Price_List__c, OCD_IA_Price_List__c FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			System.debug(logginglevel.info, 'q='+quoteHeaderObj);
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);    		      
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
			REVVY__MnQuote__c IDNQuote = quoteHeaderObj.clone(false, false, false, false);
			IDNQuote.RecordTypeId = Schema.SObjectType.REVVY__MnQuote__c.getRecordTypeInfosByName().get('IDN').getRecordTypeId();
			IDNQuote.OCD_CC_Price_List__c = quoteHeaderObj.OCD_CC_Price_List__c;
			IDNQuote.OCD_IA_Price_List__c = quoteHeaderObj.OCD_IA_Price_List__c;
			IDNQuote.IDN_Type__c = 'Base Reagent Price';
			IDNQuote.Ship_To_Customer_Number_for_Quote__c='1234';
			IDNQuote.REVVY__Expiration_Date__c = Date.Today().addDays(30);
			IDNQuote.OCD_Billing_ISO_Country_Code__c='US';
			insert IDNQuote;
			Integer lineCount = [SELECT count() FROM REVVY__MnQuoteItem__c where revvy__quote__c = :quoteHeaderObj.id];
			system.debug('---------' + lineCount);
			set<Id> qidSet = new set<Id> {quoteHeaderObj.id};
			OCD_IDNAddMembersBatchable b = new OCD_IDNAddMembersBatchable(qidSet, IDNQuote.Id, lineCount);
			Map<String, Schema.SObjectField> fieldsMap = Schema.SobjectType.REVVY__MnQuoteItem__c.fields.getMap();
	   	 	String sfields = OCDMNQuoteUtility.getObjectFields(fieldsMap);
			String criteria = ' where REVVY__Quote__c in :qidSet';
			String query = OCDMNQuoteUtility.buildSQLStatement(sfields, 'REVVY__MnQuoteItem__c', criteria);
			List<REVVY__MnQuoteItem__c> quoteLis = Database.query(query);
			b.createQuoteLineItems(quoteLis);
			list<REVVY__MnQuoteItemSubLine__c> subLines = [Select r.REVVY__Price__c, r.Id From REVVY__MnQuoteItemSubLine__c r where revvy__quoteitem__r.revvy__quote__c = :IDNQuote.Id];
			for(REVVY__MnQuoteItemSubLine__c s : subLines) {
				s.revvy__price__c = 1;
			}
			update sublines;
			OCD_IDNBaseReagentBatchable b2 = new OCD_IDNBaseReagentBatchable(IDNQuote.Id);
			Database.executeBatch(b2, 200);
		}
		catch(Exception e)
		{
			System.debug('-------------------------------------------------err msg =' + e.getMessage() + 'statck trace : ' + e.getStackTraceString());
			throw e;
		} 

		Test.stopTest();
    }
}