src/objects/REVVY__MnCatalogNode__c.object
<CustomObject>
    <fields>
        <fullName>EC_Reportable_Result_Billing_Code__c</fullName>
        <description>Europe Reportable Result Billing Code</description>
        <label>EC Reportable Result Billing Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <picklist>
            <picklistValues>
                <fullName>Reagent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accessory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warranty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade-In</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>US_Reportable_Result_Billing_Code__c</fullName>
        <label>US Reportable Result Billing Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Parent_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Quote</label>
        <referenceTo>REVVY__MnQuote__c</referenceTo>
        <relationshipLabel>IDN Member Quotes</relationshipLabel>
        <relationshipName>Parent_Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OCD_Site_Index__c</fullName>
        <label>Site Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <displayFormat>Q{00000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>ID</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>Annual_Usage_Volumes__c</fullName>
        <label>Annual Usage Volumes</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Local_SKU_Id__c</fullName>
        <label>Local SKU Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCD_Accessory_Add_On__c</fullName>
        <description>Accessory Add On</description>
        <label>Accessory Add On</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Annual_Reportable_Result_Volume__c</fullName>
        <formula>Annual_Patient_Volumes__c  +  Annual_Usage_Panel__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual Reportable Result Volume</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OCD_CPRR_Base_Price__c</fullName>
        <formula>OCD_Overridden_Price__c * ( Annual_Usage_Volumes__c / OCD_Annual_Reportable_Result_Volume__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>CPRR Base Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_CPRR_Price__c</fullName>
        <label>Price with Add Ons</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Capital_Add_On__c</fullName>
        <description>Capital Add On</description>
        <label>Capital Add On</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Consumable_Add_On__c</fullName>
        <description>Consumable Add On</description>
        <label>Consumable Add On</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Managed_Service_Fee__c</fullName>
        <label>Managed Service Fee</label>
        <precision>10</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Name_Misc__c</fullName>
        <label>Name Misc</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCD_Other_Add_On__c</fullName>
        <description>Other Add On</description>
        <label>Other Add On</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Overridden_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Final Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Reagent_Base_Price__c</fullName>
        <description>Reagent Base Price = Final Price * (Usage Volume)/(Patient Volume)</description>
        <label>Reagent Base Price</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Service_Add_On__c</fullName>
        <description>Service Add On</description>
        <label>Service Add On</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Site_Index__c</fullName>
        <label>Site Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OCD_Total_Price__c</fullName>
        <description>Total Price including sub-lines</description>
        <formula>REVVY__One_Time_Extended_Price_F__c *  REVVY__Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVVY__Catalog_Node__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Unique ID of the product associated with this quote item.</description>
        <inlineHelpText>Unique ID of the product associated with this quote item.</inlineHelpText>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>REVVY__MnCatalogNode__c.REVVY__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnCatalogNode__c.REVVY__Type__c</field>
                <operation>equals</operation>
                <value>Bundle</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>REVVY__MnCatalogNode__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>QuoteItems</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>Quote Item ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>REVVY__Price__c</fullName>
        <description>List price of product for this quote.</description>
        <inlineHelpText>List price of product for this quote.</inlineHelpText>
        <label>List Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVVY__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Number of units.</description>
        <inlineHelpText>Number of units.</inlineHelpText>
        <label>Qty</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REVVY__Quote__c</fullName>
        <description>Unique ID of the quote that this quote item belongs to.</description>
        <inlineHelpText>Unique ID of the quote that this quote item belongs to.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>REVVY__MnQuote__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>QuoteItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItemSubLine__c.object
<CustomObject>
    <fields>
        <fullName>Local_SKU_Id__c</fullName>
        <label>Local SKU Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCD_Managed_Service_Fee__c</fullName>
        <label>Managed Service Fee</label>
        <precision>10</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Overridden_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Overridden Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Parent_Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This lookup field is used to display quote sub-line on quote page as a related list.</description>
        <label>Parent Quote</label>
        <referenceTo>REVVY__MnQuote__c</referenceTo>
        <relationshipLabel>Quote Item Sub Line</relationshipLabel>
        <relationshipName>Quote_Item_Sub_Line</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OCD_Site_Index__c</fullName>
        <label>Site Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <description>Product Type of Product. Used in Roll Up formulae.</description>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__Catalog_Node__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Unique Salesforce ID for the product that this price list line refers to.</description>
        <inlineHelpText>Unique Salesforce ID for the product that this price list line refers to.</inlineHelpText>
        <label>Product</label>
        <referenceTo>REVVY__MnCatalogNode__c</referenceTo>
        <relationshipLabel>QuoteItemSubLine</relationshipLabel>
        <relationshipName>QuoteItemSubLine</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Deprecated</description>
        <externalId>true</externalId>
        <inlineHelpText>Deprecated</inlineHelpText>
        <label>Deprecated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>REVVY__Price__c</fullName>
        <description>List price of product.</description>
        <inlineHelpText>List price of product.</inlineHelpText>
        <label>List Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVVY__Quantity__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Quantity of products.</description>
        <inlineHelpText>Quantity of products.</inlineHelpText>
        <label>Qty</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REVVY__QuoteItem__c</fullName>
        <description>Unique ID of the line item (i.e., the quote item) in the quote.</description>
        <inlineHelpText>Unique ID of the line item (i.e., the quote item) in the quote.</inlineHelpText>
        <label>Quote Item</label>
        <referenceTo>REVVY__MnQuoteItem__c</referenceTo>
        <relationshipLabel>QuoteItemSubLine</relationshipLabel>
        <relationshipName>QuoteItemSubLine</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/classes/OCD_IDNBaseReagentBatchable.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @deprecated
*
* @group Network Quote
* @group-content ../../ApexDocContent/OCD_IDNBaseReagentBatchable.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou        10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

public with sharing class OCD_IDNBaseReagentBatchable implements Database.Batchable<sObject>, database.stateful {
	private Id parentQuoteId;
    private String query;
    List<String> errorMsg = new List<String>();
	public OCD_IDNBaseReagentBatchable(Id parentQuoteId) {
		this.parentQuoteId = parentQuoteId;
		query = 'Select REVVY__Catalog_Node__r.revvy__Id__c, Revvy__Quote__r.OCD_Parent_Quote__c, Revvy__Quote__c, ' + 
				'REVVY__Catalog_Node__r.Product_Type__c, OCD_Annual_Reportable_Result_Volume__c, Annual_Usage_Volumes__c, '+
				'REVVY__Quantity__c, OCD_Managed_Service_Fee__c, OCD_Overridden_Price__c, REVVY__Price__c, OCD_CPRR_Price__c, '+
				'OCD_Reagent_Base_Price__c, OCD_Name_Misc__c, Local_SKU_Id__c, REVVY__Catalog_Node__r.US_Reportable_Result_Billing_Code__c, '+
				'REVVY__Catalog_Node__r.EC_Reportable_Result_Billing_Code__c, REVVY__Catalog_Node__c , OCD_CPRR_Base_Price__c, '+
				'OCD_Total_Price__c, OCD_Capital_Add_On__c, OCD_Accessory_Add_On__c, OCD_Service_Add_On__c, OCD_Other_Add_On__c, '+
				'OCD_Consumable_Add_On__c From REVVY__MnQuoteItem__c where Revvy__Quote__r.OCD_Parent_Quote__c = :parentQuoteId';
	}   
	

	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	} 
/*	
	public static void test() {
		string testId = 'a3y29000000Yajd';
		list<REVVY__MnQuoteItem__c> test = [Select REVVY__Catalog_Node__r.revvy__Id__c, Revvy__Quote__r.OCD_Parent_Quote__c, Revvy__Quote__c, 
				REVVY__Catalog_Node__r.Product_Type__c, OCD_Annual_Reportable_Result_Volume__c, Annual_Usage_Volumes__c, 
				REVVY__Quantity__c, OCD_Managed_Service_Fee__c, OCD_Overridden_Price__c, REVVY__Price__c, OCD_CPRR_Price__c,
				OCD_Reagent_Base_Price__c, OCD_Name_Misc__c, Local_SKU_Id__c, REVVY__Catalog_Node__r.US_Reportable_Result_Billing_Code__c,
				REVVY__Catalog_Node__r.EC_Reportable_Result_Billing_Code__c, REVVY__Catalog_Node__c , OCD_CPRR_Base_Price__c,
				OCD_Total_Price__c, OCD_Capital_Add_On__c, OCD_Accessory_Add_On__c, OCD_Service_Add_On__c, OCD_Other_Add_On__c, 
				OCD_Consumable_Add_On__c From REVVY__MnQuoteItem__c where Revvy__Quote__r.OCD_Parent_Quote__c = :testId];
		OCD_IDNBaseReagentBatchable b = new OCD_IDNBaseReagentBatchable('a3y29000000Yajd');
		b.execute(null, test);
	}
	*/
	
	public void execute(Database.BatchableContext BC, List<sObject> scope) {
		integer index = 1;
		list<REVVY__MnQuoteItem__c> updatedList = new list<REVVY__MnQuoteItem__c> ();
		list<Id> qiList = new list<Id>();
		for(sObject s : scope) {
			qiList.add(s.Id);
		}
		system.debug('qiList size =' + qiList.size());
		list<REVVY__MnQuoteItemSubLine__c> sublines = [Select Id, REVVY__QuoteItem__c From REVVY__MnQuoteItemSubLine__c where REVVY__QuoteItem__c in :qiList];
		map<String, list<REVVY__MnQuoteItemSubLine__c> > qi2sublineMap = new map<String, list<REVVY__MnQuoteItemSubLine__c> >();
		for(REVVY__MnQuoteItemSubLine__c sub : sublines) {
			if(!qi2sublineMap.containsKey(sub.REVVY__QuoteItem__c)) {
				qi2sublineMap.put(sub.REVVY__QuoteItem__c, new list<REVVY__MnQuoteItemSubLine__c>());
			}
			qi2sublineMap.get(sub.REVVY__QuoteItem__c).add(sub);
		}
		
		List<OCD_IDN_Quote_Item_Reagent_Rollup__c> rollupList = new List<OCD_IDN_Quote_Item_Reagent_Rollup__c>();
		
		integer rollupIdx = 1;
		for(sObject s : scope) {
			REVVY__MnQuoteItem__c qi = (REVVY__MnQuoteItem__c) s;
			system.debug('qi type =' + qi.REVVY__Catalog_Node__r.Product_Type__c);
			
			if(qi.REVVY__Catalog_Node__r.Product_Type__c == 'Reagent') {
				system.debug('qi parent quote =' + qi.Revvy__Quote__r.OCD_Parent_Quote__c);
				rollupList.add( new OCD_IDN_Quote_Item_Reagent_Rollup__c(
					Revvy_Quote__c = qi.Revvy__Quote__c,
					z_Parent_Quote__c = qi.Revvy__Quote__r.OCD_Parent_Quote__c,
					Annual_Reportable_Result_Volume__c=qi.OCD_Annual_Reportable_Result_Volume__c,
					Annual_Usage_Volumes__c=qi.Annual_Usage_Volumes__c,
					Catalog_Node__c=qi.REVVY__Catalog_Node__c,
					CPRR_Base_Price__c=qi.OCD_Reagent_Base_Price__c,
					Final_Price__c=qi.OCD_Overridden_Price__c,
					Id__c=qi.Revvy__Quote__c + '_' +qi.Revvy__Quote__r.OCD_Parent_Quote__c + '_' + qi.REVVY__Catalog_Node__r.revvy__Id__c + '_'+ string.valueOf(rollupIdx++),
					List_Price__c=qi.REVVY__Price__c,
					Local_SKU_Id__c=qi.Local_SKU_Id__c,
					Managed_Service_Fee__c=qi.OCD_Managed_Service_Fee__c,
					Price_with_Add_Ons__c=qi.OCD_CPRR_Price__c,
					EC_Reportable_Result_Billing_Code__c=qi.REVVY__Catalog_Node__r.EC_Reportable_Result_Billing_Code__c,
					Qty__c=qi.REVVY__Quantity__c,
					Reagent_Base_Price__c=qi.OCD_Reagent_Base_Price__c,
					Reportable_Result_Billing_Code__c=qi.REVVY__Catalog_Node__r.US_Reportable_Result_Billing_Code__c,
					Total_Price__c=qi.OCD_Total_Price__c,
					OCD_Roll_Up_Flag__c = false,
					OCD_Site_Index__c = index,
					OCD_Capital_Add_On__c = qi.OCD_Capital_Add_On__c,
					OCD_Accessory_Add_On__c = qi.OCD_Accessory_Add_On__c,
					OCD_Service_Add_On__c = qi.OCD_Service_Add_On__c,
					OCD_Other_Add_On__c = qi.OCD_Other_Add_On__c,
					OCD_Consumable_Add_On__c = qi.OCD_Consumable_Add_On__c,
					OCD_CPRR_Base_Price__c = qi.OCD_Reagent_Base_Price__c
				));
				qi.OCD_Site_Index__c = index;
				updatedList.add(qi);
				if(qi2sublineMap.get(qi.Id) != null) {
					for(REVVY__MnQuoteItemSubLine__c subqi : qi2sublineMap.get(qi.Id)) {
						subqi.OCD_Site_Index__c = index;
					}
				}
				index++;
			}
		}
		try {
			update updatedList;
			if(sublines.size() > 0) {
				update sublines;
			}
			if(rollupList.size() > 0) {
				insert rollupList;
			}
		} catch (Exception e) {
			errorMsg.add('The following error has occurred : ' + e.getMessage() + ' with stack trace : ' +  e.getStackTraceString());
			throw e;
		}
	}
	
	public void finish(Database.BatchableContext BC) {
		if(errorMsg.size() > 0) {
    		Revvy__MnQuote__c q = new Revvy__MnQuote__c(Id=this.parentQuoteId, Revvy__Status__c = 'IDN_Error', REVVY__ErrorMessage__c=errorMsg[0].substring(0, 254));
			update q;
    	} else {
			Revvy__MnQuote__c q = new Revvy__MnQuote__c(Id=parentQuoteId, Revvy__Status__c = 'IDN_Completed');
			update q;
		}
	}
}