src/objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Status__c</fullName>
        <description>Where the quote is in the sales cycle. The status can be draft, ready, submitted, or ordered.</description>
        <inlineHelpText>Where the quote is in the sales cycle. The status can be draft, ready, submitted, or ordered.</inlineHelpText>
        <label>Actual Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cloning in progress...</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Creating lines in progress...</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Draft in progress...</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Importing Quote Lines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDN_Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDN_Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>Distributor_Modified_Field__c</fullName>
        <description>Indicate which field(markup, Margin, or Final Transfer Price) distributor modifies in Override page</description>
        <label>Distributor Modified Field</label>
        <picklist>
            <picklistValues>
                <fullName>Margin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Markup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Transfer Price</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_Distributor_Type__c</fullName>
        <label>Distributor Type</label>
        <picklist>
            <picklistValues>
                <fullName>Markup</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Margin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_Final_Transfer_Price__c</fullName>
        <description>Final Transfer Price to the Distributor</description>
        <label>Final Transfer Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Margin__c</fullName>
        <description>Margin for Distributor based on Final End User Price</description>
        <label>Margin</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_Mark_Up__c</fullName>
        <description>Mark Up on Standard Transfer Price for Distributor</description>
        <label>Mark Up</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_No_Add_On__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If this Checkbox has a check mark for any reagent, then that reagent is not considered for Add on costs.</description>
        <label>No Add On</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OCD_Overridden_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Final Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>As Per Quote Type</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash Purchase Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_Price_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Price Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OCD_Standard_Transfer_Price__c</fullName>
        <description>Standard Transfer Price to Distributor determined from Distributor Price Plan</description>
        <label>Standard Transfer Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItemSubLine__c.object
<CustomObject>
    <fields>
        <fullName>Distributor_Modified_Field__c</fullName>
        <label>Distributor Modified Field</label>
        <picklist>
            <picklistValues>
                <fullName>Margin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Markup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Transfer Price</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_Distributor_Type__c</fullName>
        <label>Distributor Type</label>
        <picklist>
            <picklistValues>
                <fullName>Markup</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Margin</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_Final_Transfer_Price__c</fullName>
        <description>Final Transfer Price to the Distributor</description>
        <label>Final Transfer Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Margin__c</fullName>
        <description>Margin for Distributor based on Final End User Price</description>
        <label>Margin</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_Mark_Up__c</fullName>
        <label>Mark Up</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_Overridden_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Overridden Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>As Per Quote Type</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Charge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash Purchase Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_Price_Override__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Price Override</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OCD_Standard_Transfer_Price__c</fullName>
        <description>Standard Transfer Price to Distributor determined from Distributor Price Plan</description>
        <label>Standard Transfer Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/OCD_QuoteOverrideControllerTest.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @group Quote Override
* @group-content ../../ApexDocContent/OCD_QuoteOverrideControllerTest.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

@isTest
private class OCD_QuoteOverrideControllerTest {

    @testSetup static void loadData() {
		OCD_TestData.createCLTestData();
	}
    static testMethod void myUnitTest() {
         String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId = null;
		try{ 
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName); 
			quoteHeaderObj.revvy__status__c='Draft';
			update quoteHeaderObj;
			PageReference pageRef = Page.OCD_UpdatePriceUpload;
        	Test.setCurrentPage(pageRef);
        	pageRef.getParameters().put('id', quoteHeaderObj.id);
        	Test.startTest();
        	OCD_QuoteOverrideController controller = new OCD_QuoteOverrideController();
        	controller.init();
        	controller.getDistributorTypes();
        	string userLocale = controller.userLocale;
        	List<OCD_QuoteOverrideController.QuoteItem> qis = controller.thirdPartiesQIList;
        	decimal dconsumablesType = controller.dconsumablesType;
        	decimal daccessoryType = controller.daccessoryType;
        	decimal dotherType = controller.dotherType;
        	string reagentType = controller.reagentType;
        	string consumablesType = controller.consumablesType;
        	string accessoryType = controller.accessoryType;
        	string otherType = controller.otherType;
        	controller.returnToQuote();
        	Test.stopTest();
        	//controller.returnToQuote();
        	//controller.ReadFile();
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
        
        
    }
    static testMethod void myUnitTest2() {
        String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId = null;
		try{ 
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName);
			PageReference pageRef = Page.OCD_UpdatePriceUpload;
        	Test.setCurrentPage(pageRef);
        	pageRef.getParameters().put('id', quoteHeaderObj.id); 
			OCD_QuoteOverrideController controller = new OCD_QuoteOverrideController();
			Test.startTest();
			controller.getQuoteIdString();
			controller.readQuoteItem();
        	//controller.updateQuote();
        	Test.stopTest();
        	//controller.returnToQuote();
        	//controller.ReadFile();
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
        
        
    }
    
     static testMethod void myUnitTest3() {
        String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId = null;
		try{ 
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName);
			Test.startTest();
			OCD_QuoteOverrideController.calculatePrice(quoteHeaderObj.id);
			Test.stopTest();
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
        
        
    }
    
    static testMethod void myUnitTest4() {
        String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId = null;
		try{ 
			REVVY__MnQuote__c quoteHeaderObj = OCD_TestData.retrieveQuote(quoteName);
			quoteHeaderObj.revvy__status__c='Draft';
			update quoteHeaderObj;
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);   
			List<OCD_QuoteOverrideController.QuoteOverrideItem > quoteItemList = new List<OCD_QuoteOverrideController.QuoteOverrideItem >();
			for(REVVY__MnQuoteItem__c qi : qlItems) {
				OCD_QuoteOverrideController.QuoteOverrideItem qoi = new OCD_QuoteOverrideController.QuoteOverrideItem();
				qoi.sfdc_id = qi.Id;
				qoi.payment_type = qi.OCD_Payment_Type__c;
				qoi.no_add_on = string.valueOf(qi.OCD_No_Add_On__c);
				qoi.modified_field = qi.Distributor_Modified_Field__c;
				qoi.distributor_type = qi.OCD_Distributor_Type__c;
				qoi.std_transfer_price = String.valueOf(qi.OCD_Standard_Transfer_Price__c);
				qoi.markup = String.valueOf(qi.OCD_Mark_Up__c);
				qoi.margin = String.valueOf(qi.OCD_Margin__c);
				qoi.final_transfer_price = String.valueOf(qi.OCD_Final_Transfer_Price__c);
				qoi.final_price = String.valueOf(qi.OCD_Overridden_Price__c);
				qoi.price_override = String.valueOf(qi.OCD_Price_Override__c);
				quoteItemList.add(qoi);
			}    
			
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
			List<OCD_QuoteOverrideController.QuoteOverrideItem > quoteSubItemList = new List<OCD_QuoteOverrideController.QuoteOverrideItem >();
			for(REVVY__MnQuoteItemSubLine__c qi : qlItemSublines) {
				OCD_QuoteOverrideController.QuoteOverrideItem qoi = new OCD_QuoteOverrideController.QuoteOverrideItem();
				qoi.sfdc_id = qi.Id;
				qoi.payment_type = qi.OCD_Payment_Type__c;
				qoi.modified_field = qi.Distributor_Modified_Field__c;
				qoi.distributor_type = qi.OCD_Distributor_Type__c;
				qoi.std_transfer_price = String.valueOf(qi.OCD_Standard_Transfer_Price__c);
				qoi.markup = String.valueOf(qi.OCD_Mark_Up__c);
				qoi.margin = String.valueOf(qi.OCD_Margin__c);
				qoi.final_transfer_price = String.valueOf(qi.OCD_Final_Transfer_Price__c);
				qoi.final_price = String.valueOf(qi.OCD_Overridden_Price__c);
				qoi.price_override = String.valueOf(qi.OCD_Price_Override__c);
				quoteSubItemList.add(qoi);
			}       
			Test.startTest();
			OCD_QuoteOverrideController.calculatePrice(quoteHeaderObj.id);
			OCD_QuoteOverrideController ctrl = new OCD_QuoteOverrideController();
			ctrl.nameFile = 'test';
			ctrl.contentFile = blob.valueOf('test');
			ctrl.retURL = 'test';
			ctrl.dmarkupMargin = 2.3;
			ctrl.markupMarginList = new List<SelectOption> ();
			ctrl.otherTypeList = new List<SelectOption> ();
			ctrl.readQuoteItem();
			ctrl.dreagentType = 0.0;
			OCD_QuoteOverrideController.getPrice(quoteHeaderObj.Id);
			OCD_QuoteOverrideController.updateQuoteLines(quoteItemList);
			OCD_QuoteOverrideController.updateQuoteSublines(quoteSubItemList);
			Test.stopTest();
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
        
        
    }
}