src/objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>Customer_ID__c</fullName>
        <formula>REVVY__Account__r.Customer_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Customer ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IDN_Type__c</fullName>
        <label>IDN Type</label>
        <picklist>
            <picklistValues>
                <fullName>All in One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Base Reagent Price</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_Billing_ISO_Country_Code__c</fullName>
        <label>Billing ISO Country Code</label>
        <picklist>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_CC_Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Price Plan</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3 AND 4) OR 5</booleanFilter>
            <errorMessage>Invalid CC Price Plan. Please select valid CC Price Plan</errorMessage>
            <filterItems>
                <field>REVVY__MnPriceList__c.LOB__c</field>
                <operation>equals</operation>
                <value>CC</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnPriceList__c.Is_Valid__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnPriceList__c.Country_applicability__c</field>
                <operation>equals</operation>
                <valueField>$Source.OCD_Billing_ISO_Country_Code__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.REVVY__Status__c</field>
                <operation>equals</operation>
                <value>Cloning in progress..., Creating lines in progress..., Draft, Draft in progress..., Importing Quote Lines, Ready, Submitted, IDN_Completed, IDN_Error</value>
            </filterItems>
            <filterItems>
                <field>$Source.REVVY__Status__c</field>
                <operation>equals</operation>
                <value>Ordered</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>REVVY__MnPriceList__c</referenceTo>
        <relationshipLabel>Revvy Quotes (CC Price Plan)</relationshipLabel>
        <relationshipName>CC_Price_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OCD_IA_Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IA Price Plan</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3 AND 4) OR 5</booleanFilter>
            <errorMessage>Invalid IA Price Plan. Please select valid IA Price Plan</errorMessage>
            <filterItems>
                <field>REVVY__MnPriceList__c.LOB__c</field>
                <operation>equals</operation>
                <value>IA</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnPriceList__c.Is_Valid__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnPriceList__c.Country_applicability__c</field>
                <operation>equals</operation>
                <valueField>$Source.OCD_Billing_ISO_Country_Code__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.REVVY__Status__c</field>
                <operation>equals</operation>
                <value>Cloning in progress..., Creating lines in progress..., Draft, Draft in progress..., Importing Quote Lines, Ready, Submitted, IDN_Completed, IDN_Error</value>
            </filterItems>
            <filterItems>
                <field>$Source.REVVY__Status__c</field>
                <operation>equals</operation>
                <value>Ordered</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>REVVY__MnPriceList__c</referenceTo>
        <relationshipLabel>Revvy Quotes (IA Price Plan)</relationshipLabel>
        <relationshipName>IA_Price_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OCD_Quote_Type__c</fullName>
        <inlineHelpText>Purchase, Lease, Monthly Payment, CPRR, CPT, Reagent Rental, Managed Service</inlineHelpText>
        <label>Quote Type</label>
        <picklist>
            <picklistValues>
                <fullName>Purchase</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPRR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reagent Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDN Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>REVVY__Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Unique ID of the account that is associated with the quote.</description>
        <inlineHelpText>Unique ID of the account that is associated with the quote.</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <errorMessage>You should assign only group accounts to group quotes</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Group Quote</value>
            </filterItems>
            <filterItems>
                <field>Account.REVVY__MnIsGroupAccount__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Group Quote</value>
            </filterItems>
            <filterItems>
                <field>Account.REVVY__MnIsGroupAccount__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Revvy Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Expiration_Date__c</fullName>
        <defaultValue>NOW() +   VALUE( $Label.REVVY__MnDefaultQuoteExpirationDays )</defaultValue>
        <description>Date when the quote expires.</description>
        <inlineHelpText>Date when the quote expires.</inlineHelpText>
        <label>Expires</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ship_To_Customer_Number_for_Quote__c</fullName>
        <description>The Ship to Customer for the quote. This is one of the number in the Ship-To Customer Numbers field on the Account</description>
        <inlineHelpText>Enter Ship To Customer number for quote  from the list of customer numbers in the Ship-To Customer Numbers on the Account</inlineHelpText>
        <label>Enter Ship To Customer Number for Quote</label>
        <length>8</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItem__c.object
<CustomObject>
</CustomObject>

src/objects/REVVY__MnQuoteItemSubLine__c.object
<CustomObject>
</CustomObject>

src/classes/OCD_IDNMembersControllerTest.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @group Network Quote
* @group-content ../../ApexDocContent/OCD_IDNMembersControllerTest.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

@isTest
public with sharing class OCD_IDNMembersControllerTest {

	@testSetup static void loadData() {
		OCD_TestData.createCLTestData(); 
	}
	
	static testMethod void purchaseGetPricesTest()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, REVVY__Account__c, REVVY__Account__r.Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			System.debug(logginglevel.info, 'q='+quoteHeaderObj);
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);    		      
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
			Account acc = [Select Id 
		    From Account where ID = : quoteHeaderObj.REVVY__Account__r.Id]; 
		    Account childAcc = new Account();
		    childAcc.Name = 'UTC_AccountParent';
		    childAcc.ParentId = acc.Id;
		    insert childAcc;
 
		    System.debug(logginglevel.info, 'acc='+acc);
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
			}
			
			ApexPages.StandardController stdCtrl = new ApexPages.StandardController(quoteHeaderObj);
			OCD_IDNMembersController Ctrl = new OCD_IDNMembersController(stdCtrl);
			Ctrl.selectAllAccount = true;
			Ctrl.selectAllQuote = true;
			Ctrl.next();
			Ctrl.previous();
			Ctrl.Cancel();
			Ctrl.submitMemberSelection();
			Ctrl.executeSelectAllAccount();
			Ctrl.executeSelectAllQuote();
			OCD_IDNMembersController.RevvyQuote rq = new OCD_IDNMembersController.RevvyQuote();
			
			quoteHeaderObj.REVVY__Account__c = childAcc.Id;
			quoteHeaderObj.OCD_Quote_Type__c = 'IDN Member';
			update quoteHeaderObj;
			
			for(OCD_IDNMembersController.IDNMember idnm: Ctrl.idnMemberList)
			{
	
				idnm.selected=true;
			}		
			for(OCD_IDNMembersController.RevvyQuote q: Ctrl.quoteList)
			{
	
				q.selected=true;
			}	
			Ctrl.next();
			Ctrl.submitMemberSelection();
			Ctrl.executeSelectAllAccount();
			Ctrl.executeSelectAllQuote();
			System.debug(logginglevel.info, 'Ctrl.selectAllAccount='+Ctrl.selectAllAccount);
			System.debug(logginglevel.info, 'Ctrl.selectAllQuote='+Ctrl.selectAllQuote);
			system.assert(Ctrl != null);
			ctrl.createQuoteLineItems();
		}
		catch(Exception e)
		{
			System.debug('-------------------------------------------------err msg =' + e.getMessage() + 'statck trace : ' + e.getStackTraceString());
		} 

		Test.stopTest();
		
	} //end static testMethod void getPricesTest()

	static void populateIDNMemberList(Id quoteId) {
		//List<IDNMember> idnMemberList = new List<IDNMember>();
		Set<Id> accIdSet = new Set<Id>();
		for(REVVY__MnQuote__c q:[Select Id, REVVY__Account__c, REVVY__Account__r.Name, REVVY__Account__r.Id 
		                          From REVVY__MnQuote__c 
		                         where Id =:quoteId limit 1]) {			
			accIdSet.add(q.REVVY__Account__c);
			//idnAccount = q.REVVY__Account__r;
			System.debug(logginglevel.info, 'accIdSet='+accIdSet);
			
		}
		for(Account acc:[Select Id, Name, Customer_ID__c, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry 
		                  From Account where ParentId in :accIdSet]){
			//IDNMember idnM = new IDNMember();
			System.debug(logginglevel.info, 'acc='+acc);
		}
	}

	static testMethod void myUnitTest() {
        String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, REVVY__Account__c, REVVY__Account__r.Id, name, OCD_CC_Price_List__c, OCD_IA_Price_List__c FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			System.debug(logginglevel.info, 'q='+quoteHeaderObj);
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);    		      
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
			REVVY__MnQuote__c IDNQuote = quoteHeaderObj.clone(false, false, false, false);
			IDNQuote.RecordTypeId = Schema.SObjectType.REVVY__MnQuote__c.getRecordTypeInfosByName().get('IDN').getRecordTypeId();
			IDNQuote.OCD_CC_Price_List__c = quoteHeaderObj.OCD_CC_Price_List__c;
			IDNQuote.OCD_IA_Price_List__c = quoteHeaderObj.OCD_IA_Price_List__c;
			IDNQuote.IDN_Type__c = 'Base Reagent Price';
			IDNQuote.REVVY__Expiration_Date__c = Date.Today().addDays(30);
			IDNQuote.OCD_Billing_ISO_Country_Code__c='US';
			IDNQuote.Ship_To_Customer_Number_for_Quote__c = '12345';
			quoteHeaderObj.Ship_To_Customer_Number_for_Quote__c = '12345';
			update quoteHeaderObj;
			insert IDNQuote;
			List<OCD_Global_Variable__c> gvs = new List<OCD_Global_Variable__c>{
					new OCD_Global_Variable__c(name='QIAsAttachmentBatchSize', value__c ='50'),
					new OCD_Global_Variable__c(name='QIAsAttachmentLimitSize', value__c ='1'),
					new OCD_Global_Variable__c(name='QIReagentUpdateBatchSize', value__c ='100')
			};
			insert gvs;
			OCD_IDNMembersController.IDNmemberRemoteStatus status =
				OCD_IDNMembersController.setupChildrenQuotes(IDNQuote.Id, new List<String> {quoteHeaderObj.id});
			IDNQuote.IDN_Type__c = 'All in One';
			update IDNQuote;
			status =
				OCD_IDNMembersController.setupChildrenQuotes(IDNQuote.Id, new List<String> {quoteHeaderObj.id});
			OCD_IDNMembersController.addMembers(IDNQuote.Id, quoteHeaderObj.id);
			
			OCD_IDNMembersController.getPrice(IDNQuote.Id);
			OCD_IDNMembersController.saveAttachmentsAsQuote(IDNQuote.Id, 0, 1);
			OCD_IDNMembersController.updateBaseReagentPrice(IDNQuote.Id, 0, 10);
			OCD_IDNMembersController.updateTradeInValues(IDNQuote.Id);
			OCD_IDNMembersController.completeIDNProcess(IDNQuote.Id, 'IDN_Completed');
			OCD_IDNMembersController.getPrice(null);
			OCD_IDNMembersController.saveAttachmentsAsQuote(null, 0, 1);
			OCD_IDNMembersController.updateBaseReagentPrice(null, 0, 10);
			OCD_IDNMembersController.updateTradeInValues(null);
			OCD_IDNMembersController.completeIDNProcess(null, 'IDN_Completed');
			
		}
		catch(Exception e)
		{
			System.debug('-------------------------------------------------err msg =' + e.getMessage() + 'statck trace : ' + e.getStackTraceString());
			throw e;
		} 

		Test.stopTest();
        
    }
    static testMethod void myUnitTest2() {
        String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, REVVY__Account__c, REVVY__Account__r.Id, name, OCD_CC_Price_List__c, OCD_IA_Price_List__c FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			System.debug(logginglevel.info, 'q='+quoteHeaderObj);
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);    		      
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
			REVVY__MnQuote__c IDNQuote = quoteHeaderObj.clone(false, false, false, false);
			IDNQuote.RecordTypeId = Schema.SObjectType.REVVY__MnQuote__c.getRecordTypeInfosByName().get('IDN').getRecordTypeId();
			IDNQuote.OCD_CC_Price_List__c = quoteHeaderObj.OCD_CC_Price_List__c;
			IDNQuote.OCD_IA_Price_List__c = quoteHeaderObj.OCD_IA_Price_List__c;
			IDNQuote.IDN_Type__c = 'Base Reagent Price';
			IDNQuote.REVVY__Expiration_Date__c = Date.Today().addDays(30);
			IDNQuote.OCD_Billing_ISO_Country_Code__c='US';
			IDNQuote.Ship_To_Customer_Number_for_Quote__c = '12345';
			quoteHeaderObj.Ship_To_Customer_Number_for_Quote__c = '12345';
			update quoteHeaderObj;
			insert IDNQuote;
			List<OCD_Global_Variable__c> gvs = new List<OCD_Global_Variable__c>{
					new OCD_Global_Variable__c(name='QIAsAttachmentBatchSize', value__c ='50'),
					new OCD_Global_Variable__c(name='QIAsAttachmentLimitSize', value__c ='1'),
					new OCD_Global_Variable__c(name='QIReagentUpdateBatchSize', value__c ='100')
			};
			insert gvs;
			OCD_IDNMembersController.IDNmemberRemoteStatus status =
				OCD_IDNMembersController.setupGetPriceSteps(IDNQuote.Id);
			IDNQuote.IDN_Type__c = 'All in One';
			update IDNQuote;
		}
		catch(Exception e)
		{
			System.debug('-------------------------------------------------err msg =' + e.getMessage() + 'statck trace : ' + e.getStackTraceString());
			throw e;
		} 

		Test.stopTest();
        
    }

}