src/objects/REVVY__MnPriceList__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>Price List ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/REVVY__MnPriceListLine__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Product_Type__c</fullName>
        <description>to display in Pricelist lines</description>
        <formula>TEXT( REVVY__Product__r.Product_Type__c )</formula>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>Price List Line ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>REVVY__PriceList__c</fullName>
        <description>Unique ID of the price list that this price list line belongs to.</description>
        <inlineHelpText>Unique ID of the price list that this price list line belongs to.</inlineHelpText>
        <label>Price List Name</label>
        <referenceTo>REVVY__MnPriceList__c</referenceTo>
        <relationshipLabel>Price List Lines</relationshipLabel>
        <relationshipName>PriceListLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>REVVY__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Unique Salesforce ID for the product that this price list line refers to.</description>
        <inlineHelpText>Unique Salesforce ID for the product that this price list line refers to.</inlineHelpText>
        <label>Product Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>REVVY__MnCatalogNode__c.REVVY__AllowPricing__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>REVVY__MnCatalogNode__c</referenceTo>
        <relationshipLabel>Price List Lines</relationshipLabel>
        <relationshipName>Price_List_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/classes/OCD_PriceLIstModelOptionViewBatchable.cls
public with sharing class OCD_PriceLIstModelOptionViewBatchable implements Database.Batchable<sObject>, Database.stateful {
	public String query { get; set; }
	public OCD_PriceLIstModelOptionViewBatchable() {
		query = 'Select Id from REVVY__MnPriceList__c';	
    }   
    public Database.QueryLocator start(Database.BatchableContext BC) {
    	return Database.getQueryLocator(query);
    } 
    public void execute(Database.BatchableContext BC, List<sObject> scope) {
    	List<REVVY__MnPriceList__c> pricePlanList = (List<REVVY__MnPriceList__c>)scope;
    	List<String> productIds = new List<String>();
    	for(REVVY__MnPriceList__c pp : pricePlanList) {
	    	for(REVVY__MnPriceListLine__c priceLI :
	    		[Select REVVY__PriceList__c, REVVY__Id__c, OCD_Product_Type__c, Id From REVVY__MnPriceListLine__c r where REVVY__PriceList__c = :pp.Id]) {
	    		productIds.add(priceLI.Revvy__Product__c);			
	    	}	
	    	List<REVVY__MnConfigEngineOption__c> options = [Select REVVY__Option_Group__r.revvy__Id__c, REVVY__Label__c, 
											REVVY__Catalog_Node__r.product_type__c, REVVY__Catalog_Node__r.revvy__Id__c, Id From REVVY__MnConfigEngineOption__c 
											where REVVY__Catalog_Node__r.revvy__Id__c in :productIds ];
			system.debug('-----------' + options);									
			Map<String, OCD_ModelPPController.OptionItem> sku2OptionMap = new Map<String, OCD_ModelPPController.OptionItem>();
			for(REVVY__MnConfigEngineOption__c option : options) {
				
			}
    	}
    	
    }
 	public void finish(Database.BatchableContext BC) {
 	
 	}
}