src/objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>IDN_Type__c</fullName>
        <label>IDN Type</label>
        <picklist>
            <picklistValues>
                <fullName>All in One</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Base Reagent Price</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_Billing_ISO_Country_Code__c</fullName>
        <label>Billing ISO Country Code</label>
        <picklist>
            <picklistValues>
                <fullName>AD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>OCD_CC_Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CC Price Plan</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3 AND 4) OR 5</booleanFilter>
            <errorMessage>Invalid CC Price Plan. Please select valid CC Price Plan</errorMessage>
            <filterItems>
                <field>REVVY__MnPriceList__c.LOB__c</field>
                <operation>equals</operation>
                <value>CC</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnPriceList__c.Is_Valid__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnPriceList__c.Country_applicability__c</field>
                <operation>equals</operation>
                <valueField>$Source.OCD_Billing_ISO_Country_Code__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.REVVY__Status__c</field>
                <operation>equals</operation>
                <value>Cloning in progress..., Creating lines in progress..., Draft, Draft in progress..., Importing Quote Lines, Ready, Submitted, IDN_Completed, IDN_Error</value>
            </filterItems>
            <filterItems>
                <field>$Source.REVVY__Status__c</field>
                <operation>equals</operation>
                <value>Ordered</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>REVVY__MnPriceList__c</referenceTo>
        <relationshipLabel>Revvy Quotes (CC Price Plan)</relationshipLabel>
        <relationshipName>CC_Price_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OCD_IA_Price_List__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IA Price Plan</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2 AND 3 AND 4) OR 5</booleanFilter>
            <errorMessage>Invalid IA Price Plan. Please select valid IA Price Plan</errorMessage>
            <filterItems>
                <field>REVVY__MnPriceList__c.LOB__c</field>
                <operation>equals</operation>
                <value>IA</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnPriceList__c.Is_Valid__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnPriceList__c.Country_applicability__c</field>
                <operation>equals</operation>
                <valueField>$Source.OCD_Billing_ISO_Country_Code__c</valueField>
            </filterItems>
            <filterItems>
                <field>$Source.REVVY__Status__c</field>
                <operation>equals</operation>
                <value>Cloning in progress..., Creating lines in progress..., Draft, Draft in progress..., Importing Quote Lines, Ready, Submitted, IDN_Completed, IDN_Error</value>
            </filterItems>
            <filterItems>
                <field>$Source.REVVY__Status__c</field>
                <operation>equals</operation>
                <value>Ordered</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>REVVY__MnPriceList__c</referenceTo>
        <relationshipLabel>Revvy Quotes (IA Price Plan)</relationshipLabel>
        <relationshipName>IA_Price_List</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Unique ID of the account that is associated with the quote.</description>
        <inlineHelpText>Unique ID of the account that is associated with the quote.</inlineHelpText>
        <label>Account</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <errorMessage>You should assign only group accounts to group quotes</errorMessage>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Group Quote</value>
            </filterItems>
            <filterItems>
                <field>Account.REVVY__MnIsGroupAccount__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Group Quote</value>
            </filterItems>
            <filterItems>
                <field>Account.REVVY__MnIsGroupAccount__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Revvy Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Expiration_Date__c</fullName>
        <defaultValue>NOW() +   VALUE( $Label.REVVY__MnDefaultQuoteExpirationDays )</defaultValue>
        <description>Date when the quote expires.</description>
        <inlineHelpText>Date when the quote expires.</inlineHelpText>
        <label>Expires</label>
        <required>true</required>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Quote__c</fullName>
        <description>Unique ID of the quote that this quote item belongs to.</description>
        <inlineHelpText>Unique ID of the quote that this quote item belongs to.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>REVVY__MnQuote__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>QuoteItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItemSubLine__c.object
<CustomObject>
</CustomObject>

src/classes/OCD_IDNUpdateQuoteItemsBatchableTest.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @deprecated
*
* @group Network Quote
* @group-content ../../ApexDocContent/OCD_IDNUpdateQuoteItemsBatchableTest.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/


@isTest
private class OCD_IDNUpdateQuoteItemsBatchableTest {
@testSetup static void loadData() {
		OCD_TestData.createCLTestData(); 
	}
	static testMethod void myUnitTest1() {
		try {
			OCD_IDNUpdateQuoteItemsBatchable exp = new OCD_IDNUpdateQuoteItemsBatchable(null);
			System.assert(false);
		} catch (Exception e) {
			System.assert(true);
		}
	}
    static testMethod void myUnitTest() {
        String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, REVVY__Account__c, REVVY__Account__r.Id, name, OCD_CC_Price_List__c, OCD_IA_Price_List__c FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			System.debug(logginglevel.info, 'q='+quoteHeaderObj);
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);    		      
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
			REVVY__MnQuote__c IDNQuote = quoteHeaderObj.clone(false, false, false, false);
			IDNQuote.RecordTypeId = Schema.SObjectType.REVVY__MnQuote__c.getRecordTypeInfosByName().get('IDN').getRecordTypeId();
			
			IDNQuote.IDN_Type__c = 'Base Reagent Price';
			IDNQuote.REVVY__Expiration_Date__c = Date.Today().addDays(30);
			IDNQuote.OCD_Billing_ISO_Country_Code__c='US';
			insert IDNQuote;
			Integer lineCount = [SELECT count() FROM REVVY__MnQuoteItem__c where revvy__quote__c = :quoteHeaderObj.id];
			OCD_IDNAddMembersBatchable b = new OCD_IDNAddMembersBatchable(new set<Id> {quoteHeaderObj.id}, IDNQuote.Id, lineCount);
			b.createQuoteLineItems(qlItems);
			
			List<Attachment> attachments = new List<Attachment>();
        	integer idx = 1;
        	integer attachmentIdx = 1;
        	integer batchSize = 50;
        	List<REVVY__MnQuoteItem__c> quoteItemList = new List<REVVY__MnQuoteItem__c>();
        	List<REVVY__MnQuoteItemSubLine__c> quoteSublineItemList = new List<REVVY__MnQuoteItemSubLine__c>();
        	
        	for(REVVY__MnQuoteItem__c qli : qlItems) {
        		if(idx <= batchSize) {
        			quoteItemList.add(qli);
        			idx++;
        		} else {
        			Attachment attachment = new Attachment();
	        		attachment.Body = Blob.valueOf(JSON.serialize(quoteItemList));
	        		attachment.Name = 'quoteItem'+OCDMNQuoteUtility.convertIntegerWithPadding(integer.valueOf(attachmentIdx++), 3, '0');
	        		attachment.ParentId = quoteHeaderObj.Id; 
	        		attachments.add(attachment);
        			quoteItemList = new List<REVVY__MnQuoteItem__c>();
        			idx=1;
        			System.debug(logginglevel.info, 'Quote Item Attachment added --------------------' + attachments.size());
        		}
        	}
        	idx = 1;
        	attachmentIdx=1;
        	for(REVVY__MnQuoteItemSubLine__c qli : qlItemSublines) {
        		if(idx <= batchSize) {
        			quoteSublineItemList.add(qli);
        			idx++;
        		} else {
        			Attachment attachment = new Attachment();
	        		attachment.Body = Blob.valueOf(JSON.serialize(quoteSublineItemList));
	        		attachment.Name = 'quoteSubItem'+OCDMNQuoteUtility.convertIntegerWithPadding(integer.valueOf(attachmentIdx++), 3, '0');
	        		attachment.ParentId = quoteHeaderObj.Id;
	        		attachments.add(attachment);
        			idx = 1;
        			quoteSublineItemList = new List<REVVY__MnQuoteItemSubLine__c>();
        			System.debug(logginglevel.info, 'Quote sub Item Attachment added --------------------' + attachments.size());
        		}
        	}
        	attachmentIdx = 1;
        	Attachment quoteAttachment = new Attachment();
    		quoteAttachment.Body = Blob.valueOf(JSON.serialize(quoteHeaderObj));
    		quoteAttachment.Name = 'quoteHeader'+OCDMNQuoteUtility.convertIntegerWithPadding(integer.valueOf(attachmentIdx++), 3, '0');
    		quoteAttachment.ParentId = quoteHeaderObj.Id;
    		attachments.add(quoteAttachment);
    		System.debug(logginglevel.info, 'total attachment items size --------------------' + attachments.size());
	        insert attachments;		
	        OCD_IDNUpdateQuoteItemsBatchable exp = new OCD_IDNUpdateQuoteItemsBatchable(quoteHeaderObj.Id);
			Database.executeBatch(exp, 200);
				
		}
		catch(Exception e)
		{
			System.debug('-------------------------------------------------err msg =' + e.getMessage() + 'statck trace : ' + e.getStackTraceString());
			throw e;
		} 

		Test.stopTest();
    }
    
}