src/objects/REVVY__MnPriceList__c.object
<CustomObject>
    <fields>
        <fullName>Is_Valid__c</fullName>
        <formula>IF(REVVY__Start_Date__c &lt;= TODAY()
&amp;&amp;  REVVY__End_Date__c &gt;= TODAY()
&amp;&amp;  ISPICKVAL( REVVY__Status__c , &quot;Active&quot;)  , TRUE, FALSE)</formula>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>REVVY__End_Date__c</fullName>
        <defaultValue>date (
year(today()) +  value($Label.REVVY__MnDefaultEffectiveEndDateInYears),
month(today()),
day(today())
)</defaultValue>
        <description>Date when this price list expires.</description>
        <inlineHelpText>Date when this price list expires.</inlineHelpText>
        <label>Effective End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>REVVY__Start_Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>Date when this price list takes effect.</description>
        <inlineHelpText>Date when this price list takes effect.</inlineHelpText>
        <label>Effective Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnPriceListLine__c.object
<CustomObject>
    <fields>
        <fullName>Is_Valid__c</fullName>
        <formula>AND(AND(today()  &gt;=  REVVY__Start_Date__c ,today() &lt;  REVVY__End_Date__c ), AND(today() &gt;=  REVVY__PriceList__r.REVVY__Start_Date__c , today() &lt; REVVY__PriceList__r.REVVY__End_Date__c))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Valid</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>REVVY__End_Date__c</fullName>
        <description>Date when this price list line expires.</description>
        <inlineHelpText>Date when this price list line expires.</inlineHelpText>
        <label>Effective End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>REVVY__PriceList__c</fullName>
        <description>Unique ID of the price list that this price list line belongs to.</description>
        <inlineHelpText>Unique ID of the price list that this price list line belongs to.</inlineHelpText>
        <label>Price List Name</label>
        <referenceTo>REVVY__MnPriceList__c</referenceTo>
        <relationshipLabel>Price List Lines</relationshipLabel>
        <relationshipName>PriceListLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>REVVY__Price_List_Name__c</fullName>
        <description>Name of the price list.</description>
        <formula>REVVY__PriceList__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Name of the price list.</inlineHelpText>
        <label>Price List Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__Product_Name__c</fullName>
        <description>Name of the product.</description>
        <formula>REVVY__Product__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Name of the product.</inlineHelpText>
        <label>Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__Product__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Unique Salesforce ID for the product that this price list line refers to.</description>
        <inlineHelpText>Unique Salesforce ID for the product that this price list line refers to.</inlineHelpText>
        <label>Product Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>REVVY__MnCatalogNode__c.REVVY__AllowPricing__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>REVVY__MnCatalogNode__c</referenceTo>
        <relationshipLabel>Price List Lines</relationshipLabel>
        <relationshipName>Price_List_Lines</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Start_Date__c</fullName>
        <description>Date when this price list line goes into effect.</description>
        <inlineHelpText>Date when this price list line goes into effect.</inlineHelpText>
        <label>Effective Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
</CustomObject>

src/classes/OCDGeneicTest.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @group Get Price
* @group-content ../../ApexDocContent/OCDGeneicTest.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

@isTest
private class OCDGeneicTest
{
	@testSetup static void loadData() {
		OCD_TestData.createCLTestData();
	}
	@isTest
	static void itShould()
	{
		OCDGrpVolDiscItem di = new OCDGrpVolDiscItem();
		system.assertEquals(0, di.qty);
		system.assertEquals(null, di.basedOnPdts);
		system.assertEquals(null, di.appliedOnPdts);
		system.assertEquals(0, di.minDiscount);
		system.assertEquals(0, di.maxDiscount);
		system.assertEquals(null, di.discountGroupName);
		system.assertEquals(null, di.discountType);
		system.assertEquals(null, di.adjType);
		system.assertEquals('', di.discCode);
	}
	@isTest
	static void itShould2()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId = null;
		try{ 
			list<REVVY__MnPriceListLine__c> pls = [SELECT Id, REVVY__PriceList__r.REVVY__Start_Date__c, REVVY__PriceList__c, 
				REVVY__PriceList__r.REVVY__End_Date__c, REVVY__End_Date__c, REVVY__Start_Date__c, REVVY__Product__c, 
				REVVY__Product_Name__c, REVVY__Price_List_Name__c, Is_Valid__c FROM REVVY__MnPriceListLine__c];
			for(REVVY__MnPriceListLine__c pli : pls) {
				system.assertEquals(true, pli.Is_Valid__c);
			}
		} catch ( Exception e) {
			
		}
	}
}