src/objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Quote_Type__c</fullName>
        <inlineHelpText>Purchase, Lease, Monthly Payment, CPRR, CPT, Reagent Rental, Managed Service</inlineHelpText>
        <label>Quote Type</label>
        <picklist>
            <picklistValues>
                <fullName>Purchase</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPRR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reagent Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDN Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>REVVY__ErrorMessage__c</fullName>
        <description>Error Messages related to quote</description>
        <inlineHelpText>&gt;Error Messages related to quote</inlineHelpText>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__Status__c</fullName>
        <description>Where the quote is in the sales cycle. The status can be draft, ready, submitted, or ordered.</description>
        <inlineHelpText>Where the quote is in the sales cycle. The status can be draft, ready, submitted, or ordered.</inlineHelpText>
        <label>Actual Status</label>
        <picklist>
            <picklistValues>
                <fullName>Cloning in progress...</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Creating lines in progress...</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Draft in progress...</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Importing Quote Lines</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ordered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDN_Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDN_Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>OCD_Accessory_Add_On__c</fullName>
        <description>Accessory Add On</description>
        <label>Accessory Add On</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_CPRR_Price__c</fullName>
        <label>Price with Add Ons</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Capital_Add_On__c</fullName>
        <description>Capital Add On</description>
        <label>Capital Add On</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Consumable_Add_On__c</fullName>
        <description>Consumable Add On</description>
        <label>Consumable Add On</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_IDN_Quote_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>IDN Quote Item</label>
        <referenceTo>REVVY__MnQuoteItem__c</referenceTo>
        <relationshipLabel>Quote Line Items (IDN Quote Item)</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OCD_Other_Add_On__c</fullName>
        <description>Other Add On</description>
        <label>Other Add On</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Overridden_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Final Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Pr_Conversion_Factor__c</fullName>
        <formula>REVVY__Catalog_Node__r.Pricing_Conversion_Factor__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pricing Conversion Factor</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OCD_Pricing_Info__c</fullName>
        <defaultValue>&quot;Deductions:&quot;</defaultValue>
        <label>Pricing Info</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OCD_Product_Type__c</fullName>
        <formula>TEXT( REVVY__Catalog_Node__r.Product_Type__c )</formula>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OCD_Reagent_Base_Price__c</fullName>
        <description>Reagent Base Price = Final Price * (Usage Volume)/(Patient Volume)</description>
        <label>Reagent Base Price</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OCD_Service_Add_On__c</fullName>
        <description>Service Add On</description>
        <label>Service Add On</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>REVVY__ErrorMessage__c</fullName>
        <description>Error Messages related to quote item</description>
        <inlineHelpText>&gt;Error Messages related to quote item</inlineHelpText>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__Product_ID_F__c</fullName>
        <formula>REVVY__Catalog_Node__r.REVVY__Id__c</formula>
        <label>Product ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>REVVY__Quote__c</fullName>
        <description>Unique ID of the quote that this quote item belongs to.</description>
        <inlineHelpText>Unique ID of the quote that this quote item belongs to.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>REVVY__MnQuote__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>QuoteItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>REVVY__Unit_Price__c</fullName>
        <description>Unit price of product (list price less the discount)</description>
        <inlineHelpText>Unit price of product (list price less the discount)</inlineHelpText>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>6</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/OCD_IDNUpdatemembersBatchable.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @deprecated
*
* @group Network Quote
* @group-content ../../ApexDocContent/OCD_IDNUpdatemembersBatchable.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

global with sharing class OCD_IDNUpdatemembersBatchable implements Database.Batchable<sObject>, Database.Stateful {
	public String query;
	List<String> errorMsg = new List<String>();
	private Id quoteId;
	global OCD_IDNUpdatemembersBatchable(Id quoteId) {
    	this.quoteId = quoteId;
    	query = 'Select OCD_Reagent_Base_Price__c, REVVY__Product_ID_F__c, OCD_IDN_Quote_Item__r.OCD_CPRR_Price__c, OCD_Pricing_Info__c, ' +
    			'OCD_IDN_Quote_Item__r.OCD_Reagent_Base_Price__c, OCD_CPRR_Price__c, OCD_Overridden_Price__c, ' +
    			'OCD_IDN_Quote_Item__r.OCD_Overridden_Price__c, REVVY__Quote__r.OCD_Quote_Type__c, ' + 
    			'OCD_IDN_Quote_Item__r.OCD_Capital_Add_On__c, OCD_IDN_Quote_Item__r.OCD_Service_Add_On__c, ' + 
    			'OCD_IDN_Quote_Item__r.OCD_Accessory_Add_On__c, OCD_IDN_Quote_Item__r.OCD_Consumable_Add_On__c, ' +
    			'OCD_IDN_Quote_Item__r.OCD_Other_Add_On__c, OCD_IDN_Quote_Item__r.REVVY__Unit_Price__c, OCD_IDN_Quote_Item__r.OCD_Pr_Conversion_Factor__c From REVVY__MnQuoteItem__c where REVVY__Quote__c = :quoteId and OCD_Product_Type__c =\'Reagent\'';
	}
	/*
    public void test() {
		List<REVVY__MnQuoteItem__c> qItems = [Select OCD_Reagent_Base_Price__c, REVVY__Product_ID_F__c, OCD_IDN_Quote_Item__r.OCD_CPRR_Price__c, OCD_IDN_Quote_Item__r.OCD_Reagent_Base_Price__c, OCD_CPRR_Price__c, OCD_Overridden_Price__c, OCD_IDN_Quote_Item__r.OCD_Overridden_Price__c, REVVY__Quote__r.OCD_Quote_Type__c, OCD_IDN_Quote_Item__r.OCD_Capital_Add_On__c, OCD_IDN_Quote_Item__r.OCD_Service_Add_On__c, OCD_IDN_Quote_Item__r.OCD_Accessory_Add_On__c,
	 	OCD_IDN_Quote_Item__r.OCD_Consumable_Add_On__c, OCD_IDN_Quote_Item__r.OCD_Other_Add_On__c, OCD_IDN_Quote_Item__r.REVVY__Unit_Price__c, OCD_IDN_Quote_Item__r.OCD_Pr_Conversion_Factor__c, OCD_Pricing_Info__c From REVVY__MnQuoteItem__c where REVVY__Quote__c = :quoteId and OCD_Product_Type__c ='Reagent'];
		execute(null, (List<sObject>) qItems);	
	}
	*/
	global Database.QueryLocator start(Database.BatchableContext BC) {
    	return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<sObject> scope) {
    	/*
    	upsert new OCD_Quote_Process_Log__c(
    		Parent_Quote__c = quoteId,
    		//Quote_Operation__c = 'Get Price',
    		Quote_Process__c = 'IDN',
    		Start_Time__c = Datetime.now(),
    		Status__c = 'Clone Child Quotes',
    		//Ext_Id__c = this.parentId,
    		Ext_Id__c = quoteId,
    		Short_Note__c = 'Updating child line item CPRR Price'
    	) Ext_Id__c;
    	*/
	 	
    	try{
	    	list<REVVY__MnQuoteItem__c> updatedQIList = new list<REVVY__MnQuoteItem__c>();
	    	for(sObject o : scope) {
	    		REVVY__MnQuoteItem__c qi = (REVVY__MnQuoteItem__c) o;
	    		decimal totalAddon = null;
	    		totalAddon = null;
	    		totalAddon = null;
	    		totalAddon = null;
	    		totalAddon = null;
	    		totalAddon = null;
	    		totalAddon = null;
	    		totalAddon = null;
	    		totalAddon = null;
	    		totalAddon = null;
	    		totalAddon = null;
	    		totalAddon = null;
	    		
	    		
	    		totalAddon = OCDMNQuoteUtility.defaultDecimal(qi.OCD_IDN_Quote_Item__r.OCD_Capital_Add_On__c) +
		 					 OCDMNQuoteUtility.defaultDecimal(qi.OCD_IDN_Quote_Item__r.OCD_Service_Add_On__c) +
		 					 OCDMNQuoteUtility.defaultDecimal(qi.OCD_IDN_Quote_Item__r.OCD_Accessory_Add_On__c) +
		 					 OCDMNQuoteUtility.defaultDecimal(qi.OCD_IDN_Quote_Item__r.OCD_Consumable_Add_On__c) +
		 					 OCDMNQuoteUtility.defaultDecimal(qi.OCD_IDN_Quote_Item__r.OCD_Other_Add_On__c);
		 					 
	    		if(OCDCPRRPricing.QuoteType_CPRR.equalsIgnoreCase(qi.REVVY__Quote__r.OCD_Quote_Type__c)) {
	 				qi.OCD_IDN_Quote_Item__r.OCD_Reagent_Base_Price__c = OCDMNQuoteUtility.defaultDecimal(qi.OCD_Reagent_Base_Price__c);
	    			qi.OCD_IDN_Quote_Item__r.OCD_CPRR_Price__c = OCDMNQuoteUtility.defaultDecimal(qi.OCD_Reagent_Base_Price__c) + totalAddon;
	 			} else {
	 				system.debug('unit price=' + qi.OCD_IDN_Quote_Item__r.REVVY__Unit_Price__c + ' factor ' + qi.OCD_IDN_Quote_Item__r.OCD_Pr_Conversion_Factor__c);
	 				system.debug('qi.OCD_IDN_Quote_Item__r=' + qi.OCD_IDN_Quote_Item__r  + '  --- ' + qi.OCD_Overridden_Price__c);
	 				qi.OCD_IDN_Quote_Item__r.OCD_Overridden_Price__c = qi.OCD_Overridden_Price__c;
	 				qi.OCD_IDN_Quote_Item__r.OCD_CPRR_Price__c = qi.OCD_IDN_Quote_Item__r.OCD_Overridden_Price__c + totalAddon;
	 				
	 				//qi.OCD_CPRR_Price__c = totalAddon  + (OCDMNQuoteUtility.defaultDecimal(qi.REVVY__Unit_Price__c)/qi.OCD_Pr_Conversion_Factor__c);
	 			}
	 			qi.OCD_IDN_Quote_Item__r.OCD_Pricing_Info__c = qi.OCD_Pricing_Info__c;
	    		updatedQIList.add(qi.OCD_IDN_Quote_Item__r);
	    	}
	    	update updatedQIList;
    	} catch (Exception e) {
    		
    		system.debug(e.getStacktraceString());
    		errorMsg.add('The following error has occurred : ' + e.getMessage() + ' with stack trace : ' +  e.getStackTraceString());
    		/*
    		upsert new OCD_Quote_Process_Log__c(
	    		Parent_Quote__c = quoteId,
	    		//Quote_Operation__c = 'Get Price',
	    		Quote_Process__c = 'IDN',
	    		End_Time__c = Datetime.now(),
	    		Status__c = 'Error',
	    		//Ext_Id__c = this.parentId,
	    		Ext_Id__c = quoteId,
	    		Short_Note__c = e.getMessage()
    		) Ext_Id__c;
    		*/
    	}
    }
    public integer getMinLen(string str, integer max) {
    	integer len = str != null ? str.length() : 0;
    	len = math.min(len,max);
    	return len;
    }
    global void finish(Database.BatchableContext BC) {
    	/*
    	AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed,
     	 TotalJobItems, CreatedBy.Email
      		FROM AsyncApexJob WHERE Id =
      		:BC.getJobId()];
    	upsert new OCD_Quote_Process_Log__c(
    		Parent_Quote__c = quoteId,
    		//Quote_Operation__c = 'Get Price',
    		Quote_Process__c = 'IDN',
    		End_Time__c = Datetime.now(),
    		Status__c = 'Clone Child Quotes',
    		//Ext_Id__c = this.parentId,
    		Ext_Id__c = quoteId,
    		Short_Note__c = 'Processed ' + string.valueOf(a.JobItemsProcessed) + ' items with ' + string.valueOf(a.NumberOfErrors) + ' errors'
    	) Ext_Id__c;
    	*/
    	if(errorMsg.size() > 0) {
    		string msg = errorMsg[0];
    		integer len = msg != null ? msg.length() : 0;
    		len = math.min(len,254);
    		Revvy__MnQuote__c q = new Revvy__MnQuote__c(Id=this.quoteId, Revvy__Status__c = 'IDN_Error', REVVY__ErrorMessage__c=errorMsg[0].substring(0, getMinLen(errorMsg[0], 254)));
			update q;
    	} else {
	    	OCD_IDNBaseReagentBatchable batch = new OCD_IDNBaseReagentBatchable(quoteId);
	    	if (!Test.isRunningTest()){
	    		Database.executeBatch(batch, 100);
	    	}
    	}
    }
}