src/objects/REVVY__MnCatalogNode__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/REVVY__MnPriceList__c.object
<CustomObject>
    <fields>
        <fullName>Country_applicability__c</fullName>
        <description>ocd</description>
        <label>Country applicability</label>
        <picklist>
            <picklistValues>
                <fullName>United States</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canada</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>Price List ID</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuote__c.object
<CustomObject>
    <fields>
        <fullName>MultiFamily__c</fullName>
        <defaultValue>false</defaultValue>
        <description>User to check Multi Family Eligibility and check this box if Quote is eligible for Multi Family discount.</description>
        <inlineHelpText>Please check Multi Family Eligibility and check this box if Quote is eligible for Multi Family discount</inlineHelpText>
        <label>MultiFamily</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OCD_Apply_Managed_Services_Fee_to__c</fullName>
        <description>Product Types to which the Managed Services Fee</description>
        <inlineHelpText>Product Types to which the Managed Services Fee</inlineHelpText>
        <label>Apply Managed Services Fee to</label>
        <picklist>
            <picklistValues>
                <fullName>Accessory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consumables</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Equipment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reagent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>OCD_CC_Accessories_Discount__c</fullName>
        <label>CC Accessories Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CC_Consumable_Discount__c</fullName>
        <label>CC Consumable Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CC_Equipment_Discount__c</fullName>
        <label>CC Equipment Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CC_Other_Discount__c</fullName>
        <label>CC Other Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CC_Service_Discount__c</fullName>
        <label>CC Service Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_CC_Volume_Disc__c</fullName>
        <defaultValue>0</defaultValue>
        <label>CC Volume Disc</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_IA_Accessories_Discount__c</fullName>
        <label>IA Accessories Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_IA_Consumable_Discount__c</fullName>
        <label>IA Consumable Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_IA_Equipment_Discount__c</fullName>
        <label>IA Equipment Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_IA_Other_Discount__c</fullName>
        <label>IA Other Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_IA_Service_Discount__c</fullName>
        <label>IA Service Discount</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_IA_Volume_Disc__c</fullName>
        <defaultValue>0</defaultValue>
        <label>IA Volume Disc</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>OCD_Quote_Type__c</fullName>
        <inlineHelpText>Purchase, Lease, Monthly Payment, CPRR, CPT, Reagent Rental, Managed Service</inlineHelpText>
        <label>Quote Type</label>
        <picklist>
            <picklistValues>
                <fullName>Purchase</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lease</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPRR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reagent Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IDN Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <displayFormat>Q{00000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>ID</label>
        <type>AutoNumber</type>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItem__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Catalog_Node__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Unique ID of the product associated with this quote item.</description>
        <inlineHelpText>Unique ID of the product associated with this quote item.</inlineHelpText>
        <label>Product</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>REVVY__MnCatalogNode__c.REVVY__Type__c</field>
                <operation>equals</operation>
                <value>Product</value>
            </filterItems>
            <filterItems>
                <field>REVVY__MnCatalogNode__c.REVVY__Type__c</field>
                <operation>equals</operation>
                <value>Bundle</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>REVVY__MnCatalogNode__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>QuoteItems</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Unique ID for each record that can be used as an external ID for importing and exporting data.</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique ID for this record.</inlineHelpText>
        <label>Quote Item ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/REVVY__MnQuoteItemSubLine__c.object
<CustomObject>
    <fields>
        <fullName>REVVY__Catalog_Node__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Unique Salesforce ID for the product that this price list line refers to.</description>
        <inlineHelpText>Unique Salesforce ID for the product that this price list line refers to.</inlineHelpText>
        <label>Product</label>
        <referenceTo>REVVY__MnCatalogNode__c</referenceTo>
        <relationshipLabel>QuoteItemSubLine</relationshipLabel>
        <relationshipName>QuoteItemSubLine</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>REVVY__Id__c</fullName>
        <description>Deprecated</description>
        <externalId>true</externalId>
        <inlineHelpText>Deprecated</inlineHelpText>
        <label>Deprecated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/OCD_QuotePriceLookupTest.cls
/**
* @author Roy Lou
* @date 10/10/2016 
*
* @group Get Price
* @group-content ../../ApexDocContent/OCD_QuotePriceLookupTest.htm 
*
* @description 
* @Change History
*
*   Tag         Author              Date             Requested-BY      Description     
* *****************************************************************************************************************              
*   1.0.0      Roy Lou              10/10/2016        N/A               Initial Version                            
* *****************************************************************************************************************/

@isTest
public with sharing class OCD_QuotePriceLookupTest {
	@testSetup static void loadData() {
		OCD_TestData.createCLTestData();
	}
	
	static testMethod void commonTest()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			list<REVVY__MnPriceList__c> pls = [Select r.REVVY__Id__c, r.Id From REVVY__MnPriceList__c r];
			for(REVVY__MnPriceList__c pl : pls) {
				pl.Country_applicability__c = 'US';
			}
			
			update pls;
			OCDQuotePriceLookup.cloneCode(quoteHeaderObj.Id);
			OCDQuotePriceLookup.syncQuoteToOpportunity(quoteHeaderObj.Id);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		} 
		Test.stopTest();
		
	} //end static testMethod void getPricesTest()
	
	static testMethod void compareQuote()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			OCDQuotePriceLookup.compareQuotes(quoteHeaderObj.Id);
			OCDQuotePriceLookup.setIDNPushTopic(quoteHeaderObj.Id); 
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		} 

		Test.stopTest();
		
	} //end static testMethod void getPricesTest()
	
	static testMethod void purchaseGetPricesTest()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_IA_Volume_Disc__c=0;
				quoteHeaderObj.OCD_CC_Volume_Disc__c=0;
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		} 

		Test.stopTest();
		
	} //end static testMethod void getPricesTest()
	
	static testMethod void StrategicDiscountTest()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_IA_Accessories_Discount__c=2;
				quoteHeaderObj.OCD_IA_Consumable_Discount__c=2;
				quoteHeaderObj.OCD_IA_Equipment_Discount__c=2;
				quoteHeaderObj.OCD_IA_Service_Discount__c=2;
				quoteHeaderObj.OCD_IA_Other_Discount__c=2;
				quoteHeaderObj.OCD_IA_Volume_Disc__c=2;
				
				quoteHeaderObj.OCD_CC_Accessories_Discount__c=2;
				quoteHeaderObj.OCD_CC_Consumable_Discount__c=2;
				quoteHeaderObj.OCD_CC_Equipment_Discount__c=2;
				quoteHeaderObj.OCD_CC_Service_Discount__c=2;
				quoteHeaderObj.OCD_CC_Other_Discount__c=2;
				quoteHeaderObj.OCD_CC_Volume_Disc__c=2;
				
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		} 

		Test.stopTest();
		
	} //end static testMethod void getPricesTest()
	
	static testMethod void resetPricesTest()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
			}
			
			msg = OCDQuotePriceLookup.resetPrices(quoteId);
			
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		} 

		Test.stopTest();
		
	} //end static testMethod void getPricesTest()
	
	static testMethod void multifamilyGetPricesTest()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.MultiFamily__c=true;
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
			
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} //end static testMethod void getPricesTest()
	
	static testMethod void leaseGetPricesTest()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'Lease';
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 
	
	static testMethod void reagentRentalGetPricesTest()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'Reagent Rental';
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 
	
	static testMethod void cptGetPricesTest()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'CPT';
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 
	
	static testMethod void managedServicesGetPricesTest()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'Managed Services';
				quoteHeaderObj.OCD_Apply_Managed_Services_Fee_to__c = 'Reagent;Equipment;Consumables;Service;Accessory;Other';
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
			OCDManagedServicesPricing ms = new OCDManagedServicesPricing();
			System.assert(ms.getLocale('US') == 'US');
			
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 
	
	static testMethod void managedServicesGetPricesTest2()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'Managed Services';
				quoteHeaderObj.OCD_Apply_Managed_Services_Fee_to__c = 'Reagent;Equipment;Consumables;Service;Accessory;Other';
				update quoteHeaderObj;
			}
			List<REVVY__MnQuoteItem__c> qlItems = OCD_TestData.retrieveQuoteItems(quoteHeaderObj.Id);          
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
			List<Id> pIds = new List<String> {qlItems[0].REVVY__Catalog_Node__c, qlItems[1].REVVY__Catalog_Node__c, qlItems[2].REVVY__Catalog_Node__c};
			list<REVVY__MnCatalogNode__c> products = [Select r.Id From REVVY__MnCatalogNode__c r where Id in :pIds];
			products[0].Product_Type__c = 'Accessory';
			products[1].Product_Type__c = 'Other';
			products[2].Product_Type__c = 'Service';
			update products;
			List<Id> pIds2 = new List<String> {qlItemSublines[0].REVVY__Catalog_Node__c, qlItemSublines[1].REVVY__Catalog_Node__c};
			list<REVVY__MnCatalogNode__c> products2 = [Select r.Id From REVVY__MnCatalogNode__c r where Id in :pIds2];
			products2[0].Product_Type__c = 'Accessory';
			products2[1].Product_Type__c = 'Other';
			//products[2].Product_Type__c = 'Service';
			
			update products2;
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 
	
	static testMethod void managedServicesGetPricesTest3()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'Managed Services';
				quoteHeaderObj.OCD_Apply_Managed_Services_Fee_to__c = 'Reagent;Equipment;Consumables;Service;Accessory;Other';
				update quoteHeaderObj;
			}
			List<REVVY__MnQuoteItemSubLine__c> qlItemSublines = OCD_TestData.retrieveQuoteItemsublines(quoteHeaderObj.Id);
			
			List<Id> pIds2 = new List<String> {qlItemSublines[0].REVVY__Catalog_Node__c, qlItemSublines[1].REVVY__Catalog_Node__c};
			list<REVVY__MnCatalogNode__c> products2 = [Select r.Id From REVVY__MnCatalogNode__c r where Id in :pIds2];
			products2[0].Product_Type__c = 'Equipment';
			products2[1].Product_Type__c = 'Consumables';
			//products[2].Product_Type__c = 'Service';
			
			update products2;
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 
	
	
	static testMethod void idnMemberGetPricesTest()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'IDN Member';
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 
	
	static testMethod void monthlyRentalGetPricesTest()
	{
		String quoteName = 'CL Test Quote';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'Monthly Rental';
				update quoteHeaderObj;
			}
			
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 
	
	static testMethod void cprrGetPricesTest()
	{
		String quoteName = 'CL Test Quote';
		String sharedConsumables = '6801715';
		String  msg ;
		String quoteId=null;
		Test.startTest();
		try{
			
			
			REVVY__MnQuote__c quoteHeaderObj = [SELECT Id, name FROM REVVY__MnQuote__c WHERE Name = :quoteName LIMIT 1];
			
			if(quoteHeaderObj != null)	{
				quoteId = quoteHeaderObj.Id;
				quoteHeaderObj.OCD_Quote_Type__c = 'CPRR';
				update quoteHeaderObj;
			}
			
			List<REVVY__MnCatalogNode__c> prods = [Select Id From REVVY__MnCatalogNode__c r where REVVY__Id__c = :sharedConsumables OR REVVY__Id__c = '6801744'];
			for(REVVY__MnCatalogNode__c p : prods) {
				p.LOB__c = 'CC;IA';
			}
			update prods;
			
			List<REVVY__MnQuoteItem__c> qItems =  [Select Id, r.REVVY__Quantity__c, r.REVVY__Product_ID_F__c From REVVY__MnQuoteItem__c r 
													where REVVY__Product_ID_F__c= :sharedConsumables and REVVY__Quote__r.Name= :quoteName];
			List<REVVY__MnQuoteItemAttribute__c> qias = new List<REVVY__MnQuoteItemAttribute__c>();
			
			for(REVVY__MnQuoteItem__c qi : qItems) {
				qias.add(new REVVY__MnQuoteItemAttribute__c(REVVY__QuoteItem__c = qi.Id, REVVY__AttributeValue__c = '131', REVVY__ActualValue__c='131', ccQty__c=131,
								REVVY__CatalogAttribute__r = new REVVY__MnCatalogAttribute__c(REVVY__Id__c='ccQty')));
				qias.add(new REVVY__MnQuoteItemAttribute__c(REVVY__QuoteItem__c = qi.Id, REVVY__AttributeValue__c = '100', REVVY__ActualValue__c='100', iaQty__c=100,
								REVVY__CatalogAttribute__r = new REVVY__MnCatalogAttribute__c(REVVY__Id__c='iaQty')));
			}
			insert qias;
			msg = OCDQuotePriceLookup.getPrices(quoteId);
		}
		catch(Exception e)
		{
			System.assert(false, e.GetMessage() + '|' + e.getStackTraceString());
		}
		Test.stopTest();
		
	} 


}//End OCD_QuotePriceLookupTest